### ISSUE TITLE
Hyper

### ISSUE THREAD

**Issue by asheeeshh** [catppuccin/catppuccin#137]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Already done: https://github.com/asheeeshh/hyper

**Comment by asheeeshh** [comment]
I just noticed the background color hex, it was not intended, I'll change it right away.

About the repo name, I can change it to just `Hyper` but the npm package will still be `hypurr`, is that okay?

**Comment by asheeeshh** [comment]
Just fixed both the issues, please let me know if any further changes are needed :)

**Comment by asheeeshh** [comment]
@andreasgrafen can i keep the repo name as `hyper-catpuccin` ? ig it conflicts with the naming scheme for hyper plugins

**Comment by andreasgrafen** [comment]
It's just that the Repo itself would be nice to be the most simple version of what the port is meant to be for because that makes it easier to find when people are searching for it in the long list of repos that the Org is hosting.
So in my book it's not an issue to have the actual plugin and NPM package be named `Hypurr` or `Hyper-Catppuccin` or anything. Between the two I honestly prefer your initial pun btw. c:

Let's annoy the big boss with this, shall we? :^)
@Pocco81 What do you think? ^—^

**Comment by Pocco81** [comment]
I agree with @andreasgrafen. Something like `hyper-catppuccin` fits more appropriately as it's easier to search up and more relatable to Catppuccin than "hypurr".

Apart from that, I think the port looks great and (after fixing the issue I mentioned above) can be moved into the org 👍

Unless.... of course... @andreasgrafen spotted any other issues/has more suggestions...

**Comment by andreasgrafen** [comment]
Nah, I can't find anything to nag about. ^—^

**Comment by asheeeshh** [comment]
will change the repo name to `hyper-catpuccin`, and I'm also updating the readme using the template.

**Comment by asheeeshh** [comment]
Done with everything 😺

**Comment by asheeeshh** [comment]
changed the links to `catppuccin/hyper-catppuccin` and transferred it
