### ISSUE TITLE
Bento

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/catppuccin#1683]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
https://github.com/migueravila/Bento
https://github.com/BlueFalconHD/Bento
![](https://github.com/BlueFalconHD/Bento/raw/master/assets/preview.png)

**Comment by andreasgrafen** [comment]
This is a full for of Bento, right? That makes things a lot more complicated.
I don't think we want to re-distribute forked software – only themes for software. Especially since the original is licensed under [GPL3](https://github.com/migueravila/Bento/blob/master/License); you can't just change the license to [MIT](https://github.com/BlueFalconHD/Bento/blob/master/LICENSE). that's not how this works and could cause a lot of trouble. The theme itself is nice, but it would have to be in a way that ensures that we only deliver the theme (via stylus for example) instead of offering the whole software.
