### ISSUE TITLE
Vercel

### ISSUE THREAD

**Issue by ryanccn** [catppuccin/catppuccin#1764]
https://github.com/ryanccn/ctp-vercel

**Comment by taka0o** [comment]
Quick feedback:
![image](https://user-images.githubusercontent.com/1811016/208313095-f75fd209-6165-4d7e-bc88-005f76fe38a7.png)

On Macchiato, warnings and errors are really hard to read. I didn't test the other flavours since I'm a Macchiato user.

**Comment by ryanccn** [comment]
<img width="1199" alt="Screenshot 2022-12-19 at 08 14 50" src="https://user-images.githubusercontent.com/70191398/208326990-96f696e0-67c6-4c7f-97ca-1506ae53c26c.png">

@taka0o hmm, it looks right for me though...

maybe you have light mode turned on in Vercel's settings?

**Comment by taka0o** [comment]
Yup you were right. I had it on system preferences but I though my system was dark themed. Go figure :smiling_face_with_tear: !

**Comment by sgoudham** [comment]
Hey there, also just taking a look at this. A few comments from me:

1. For the images on the repository, it would be great if they were converted to relative image paths so that they display properly no matter what namespace they are under.

2. We should have a stylus install button, like the [DeepL](https://github.com/catppuccin/deepl) port shown below:
![image](https://user-images.githubusercontent.com/58985301/209737751-36920e42-412f-4ced-9af0-e018a66f21d0.png)
	I can see that the install link already exists but would be nice in the button format above ^^

3. For the user menu dropdown on the top right on the Latte theme, the background highlights are actually lighter when selected. To be consistent with the rest of the UI, the element should get darker when hovered upon and when selected, it should be darker. 

	Offending Highlight: (`Dashboard` is currently selected but it has a white background compared to a grey overall menu background. `Settings` is hovered upon but again a white background compared to a grey overall menu)
![image](https://user-images.githubusercontent.com/58985301/209742075-30b104cb-5171-460d-afbf-8919cd350e2e.png)

	I would expect the highlight to be more in line with the following: (`Overview` is currently selected and `Activity` is getting hovered upon)
![image](https://user-images.githubusercontent.com/58985301/209742174-f6c4b231-d5d9-45a1-b49b-23d756e66acf.png)

Hope those comments are okay!

**Comment by ryanccn** [comment]
Done in https://github.com/ryanccn/ctp-vercel/commit/9da45bbbf5e5265347bd640d433d5a7bfa6c9fe4!

**Comment by sgoudham** [comment]
Thanks for making some changes! 

Just one little thing: 
When currently on a page in the menu, the background is still white instead of the menu background. I think changing this to be the menu background would look better. What do you think? 

The highlight:
![image](https://user-images.githubusercontent.com/58985301/210267438-6859911a-2988-49dc-8fb8-8bd7c07e0f03.png)

**Comment by ryanccn** [comment]
@sgoudham hmm, I think it's actually an issue with Vercel?

When `/dashboard` is the route it is indeed highlighted as active, but on `/<user>` or `/<org>` rights "Dashboard" is not highlighted, even on the default theme.

**Comment by sgoudham** [comment]
Thanks for going ahead with the changes as mentioned in discord. I think it looks good to be transferred over!

@nekowinston will now send you an invite to the organisation. Once you've transferred the repository over, a PR can be raised to add it to the README and then we can close off this issue :tada:
