### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by brambozz** [catppuccin/catppuccin#1784]
**Are you available to help in the creation of this port? 😄**
Yes!

**Additional context 📷 (optional)**

I think I have most of the stuff done, developing here: https://github.com/brambozz/matplotlib-catppuccin

**TODO**

- [x] pip installable

**Comment by brambozz** [comment]
Package is now live at: https://pypi.org/project/catppuccin-matplotlib/ !

**Comment by nekowinston** [comment]
Just updating people on GitHub: there's been additional progress/reviews in our Discord, and AFAIK the port will get rewritten to use [catppuccin/python](https://github.com/catppuccin/python).

@brambozz I've sent you an invite to the org since there's already a package released & it's looking alright. Feel free to transfer it over anytime.

**Comment by brambozz** [comment]
Thanks! I transferred the repo to the catppuccin organization and opened an [issue](https://github.com/catppuccin/matplotlib/issues/2) to track the rewrite to catppuccin's python port.
