### ISSUE TITLE
Tutanota

### ISSUE THREAD

**Issue by ryanccn** [catppuccin/catppuccin#1807]
**Are you available to help in the creation of this port? 😄 (optional)**
https://github.com/ryanccn/ctp-tutanota

**Comment by isabelincorp** [comment]
Hey residential Tutanota user here, thank you!

So testing out the theme it looks good and works well, all that really needs work is an instruction telling the user to put Tutanota in dark mode before using the theme.

Other than that, this is ready to be transferred over!

What can be worked on later is somehow being able to color swap HTML emails because right now it is bright white.

**Comment by isabelincorp** [comment]
Oh right latte, need base/crust inverted.

**Comment by ryanccn** [comment]
> Oh right latte needs base/crust inverted.

Should be fixed

**Comment by isabelincorp** [comment]
Thanks! 
add ```> **Note** ``` to the start of ```Set Tutanota's built-in theme to either **light** if you're using Latte or **dark** if you're using the others.``` 
so that it will look something like
> **Note**  Set Tutanota's built-in theme to either **light** if you're using Latte or **dark** if you're using the others.

Then you can transfer over the repository.

**Comment by ryanccn** [comment]
Transferred :)
