### ISSUE TITLE
theme.park

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1882]
@lewisakura has made the port for [theme.park](https://github.com/lewisakura/theme.park)
It's now ready to be reviewed!

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1881

<div type='discussions-op-text'>

<sup>Originally posted by **lewisakura** January 27, 2023</sup>
### Will you make the port?

- [X] Yes, I'm willing to make the port

### How can the requested port be themed?

https://docs.theme-park.dev/custom/

### Has the requested port been themed already?

https://github.com/lewisakura/theme.park

### Any additional comments?

as previously mentioned in discord, latte is on a best case basis. theme.park is a theme framework for many apps, therefore it is impossible to fix it up on every one it supports (at time of writing, 50).</div>

**Comment by lewisakura** [comment]
5 apps, one theme (jellyfin, prowlarr, radarr, sonarr, vuetorrent)

https://user-images.githubusercontent.com/8019327/215325316-5d39f3f8-8398-49dd-8d5a-c611d5d91c28.mp4

**Comment by nekowinston** [comment]
Thanks for creating this port! I've finally had a chance to look at this, and we can transfer it over. @lewisakura I've sent you an invite.

We should set up GitHub pages for the `./flavors` folder, since `raw.githubusercontent.com` doesn't return the `Content-Type` header. We can set up a subdomain, e.g. `themepark.catppuccin.com`.

**Comment by lewisakura** [comment]
https://github.com/catppuccin/theme.park

**Comment by nekowinston** [comment]
Forgot to close this with 03c259c550e1284a0b3fcf3c7a409c6671c69db6
