### ISSUE TITLE
Dopamine

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1917]
@jayylmao has made a port for Dopamine: [jayylmao/dopamine-catppuccin](https://github.com/jayylmao/dopamine-catppuccin)
It's now ready for review!

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1914

<div type='discussions-op-text'>

<sup>Originally posted by **jayylmao** February 10, 2023</sup>
### Will you make the port?

- [X] Yes, I'm willing to make the port

### How can the requested port be themed?

This is the app in question: https://github.com/digimezzo/dopamine. It comes with a themes folder with some alternate theme files (.theme) built-in. I based my port off of these.

### Has the requested port been themed already?

https://github.com/jayylmao/dopamine-catppuccin

### Any additional comments?

_No response_</div>

**Comment by backwardspy** [comment]
hey @jayylmao thanks for your work on the theme! i've just installed it and it looks great.

there is one issue i'd like to hear your thoughts on before we transfer it to the org.

some of the buttons are hard to make out when using a light accent colour. for example these buttons on the mocha yellow theme variant:
![add folder button](https://user-images.githubusercontent.com/289746/218278274-e47805d4-ca28-4d5b-bbef-546516499fd2.png)
![return from settings button](https://user-images.githubusercontent.com/289746/218278288-bdb57f23-fc20-4c4c-81d5-14f3cd9541ae.png) (top left)

it might be a good idea to use a darker colour such as crust for the button foreground, or perhaps have the buttons as outlines rather than a solid colour if that's possible.

**Comment by jayylmao** [comment]
There doesn't seem to be an obvious way to change the color of these elements; it looks like they are hard-coded to be #fff. I can try opening an issue on the original project to request that a variable be made to allow users to change these colors.

**Comment by backwardspy** [comment]
ah, that is unfortunate. perhaps for now we could style the buttons with a darker colour such as surface0 and then bring back the accented buttons when the foreground colour becomes customisable?

**Comment by jayylmao** [comment]
I tried and the popup backgrounds are controlled by `accentColor`, which also controls some header text, so other parts of the app become unreadable.
<img width="965" alt="image" src="https://user-images.githubusercontent.com/73204320/218310027-7e7b7b48-d92c-404f-95de-d8f47542d712.png">

**Comment by backwardspy** [comment]
worth a try! :smile:
seems like we don't really have much of an option here, so let's leave it the way it is for now. i have no more to add at this stage, so whenever you're ready you may update the links in the README (image URLs et cetera) and transfer the port to the org.

let me know once you've transferred it and i'll add it to the ports list.

thanks again for your work on this!

**Comment by jayylmao** [comment]
Okay, I transferred the repository. By the way, digimezzo (Dopamine's creator) responded to my issue here: https://github.com/digimezzo/dopamine/issues/381#issuecomment-1426954905, and said that a fix for this might be added by the next preview.

**Comment by backwardspy** [comment]
thanks @jayylmao!
