### ISSUE TITLE
Blender

### ISSUE THREAD

**Issue by Dalibor-P** [catppuccin/catppuccin#2040]
### Link to repository

https://github.com/Dalibor-P/blender

### Screenshots

![Latte](https://user-images.githubusercontent.com/131712814/236824537-dd81a6b9-95b0-4a09-baed-b248d8b614ca.png)
![catwalk](https://user-images.githubusercontent.com/131712814/236824545-5f154d49-fbd6-47fb-978e-20844e234078.png)
![Frappé](https://user-images.githubusercontent.com/131712814/236824525-72bda761-d381-497d-baee-006ddd02af20.png)

### Any additional comments?

I want to continue to maintain the Latte flavor.

Other flavors are right now generated using Puccinier and need a review.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by Dalibor-P** [comment]
I have fixed some issues with the latte flavor, and created the dark theme.

![latte_preview](https://github.com/catppuccin/catppuccin/assets/131712814/03207cc8-10d5-491f-994a-aa5fa915c300)

![frappe_preview](https://github.com/catppuccin/catppuccin/assets/131712814/9aa83ece-703e-46e5-97eb-095647a4b075)

**Comment by FelipeEmos** [comment]
Nice, good work!

I have some feedback regarding the contrast
I think it's not good enough when a highlight is behind a text

![image](https://github.com/catppuccin/catppuccin/assets/10969700/6de75168-3ecd-499f-ab42-179bb15f5229)
![image](https://github.com/catppuccin/catppuccin/assets/10969700/5459213d-f1cd-4b25-8d35-0de1a4c95b7f)
The Dark theme is more problematic but the light theme is ( in my opinion ) also not ideal.

Specially for people with disabilities these contrasts may be troublesome, but also for us it can make long working hours more tiring for the view... 

### Resources
If you want help tuning the contrast I'll leave two recommendations of resources:

[Real Time Colors](https://www.realtimecolors.com/?colors=050315-fbfbfe-2f27ce-dedcff-433bff&fonts=Poppins-Poppins) is a tool that let's you preview how your website will look like. It comes with contrast checks. If you see a "check" in the color box then it's ok 
![image](https://github.com/catppuccin/catppuccin/assets/10969700/f79f2cbb-8fb5-4ab1-9a71-4546cc4e4b5b)
An `X` is bad and a `-` sign means the contrast will be troublesome for some people and some situations

[Material You Theme Builder](https://m3.material.io/theme-builder#/custom) is a little harder to apply sometimes but its results are amazing for contrast... Google did a lot of research and even came up with a different color system that better represents the Human perception of contrast ( instead of something like HSB ).
The most useful stuff in my opinion is in the bottom, the Extended Colors
![image](https://github.com/catppuccin/catppuccin/assets/10969700/4d2ce45c-0414-456f-8bff-f1c49dd21944)

I picked one of catppuccin's colors for example and it generated a really nice gradient of contrast proof tones and it also gave me combinations of `Element Colors / Container Colors` that work amazing on UI for both dark and light theme!

Maybe they are worth experimenting with, in case the existing catppuccin's palette doesn't work great for the highlighting

![image](https://github.com/catppuccin/catppuccin/assets/10969700/7398475f-4fd8-4869-bdc0-9b50d28578ef)

**Comment by Laxystem** [comment]
@FelipeEmos
> Specially for people with disabilities these contrasts may be troublesome, but also for us it can make long working hours more tiring for the view...
As a colorblind, dark mode has more contrast. Light mode is unreadable.

**Comment by backwardspy** [comment]
i'm going to close this issue based on [this comment](https://github.com/catppuccin/catppuccin/issues/2303#issuecomment-1986817068). let me know if you change your mind and we can reopen.

**Comment by os3albert** [comment]
Hey guys I think I made a great catppuccin theme for blender check it out: https://github.com/os3albert/catppuccin-4-blender

![image](https://github.com/user-attachments/assets/b2d1a738-0cdc-42ae-abeb-f6a95d8f4bea)
