### ISSUE TITLE
Raycast

### ISSUE THREAD

**Issue by rayhanadev** [catppuccin/catppuccin#2067]
### Link to repository

https://github.com/rayhanadev/raycast

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/72509475/2fa635a5-086a-41d9-8163-20633425cc1e)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hiya :wave:
Thanks for your work on this! Looks nice :D 

Since we previously discussed in [#Raycast](https://discord.com/channels/907385605422448742/1115750584692265041) on discord, I'm happy for it to be transferred over to the organisation! I've sent over an invite to you and feel free to transfer it at your earliest convenience!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**
