### ISSUE TITLE
Opera GX

### ISSUE THREAD

**Issue by isabelroses** [catppuccin/catppuccin#2068]
### Link to repository

https://github.com/isabelroses/opera-gx.git

### Screenshots

https://raw.githubusercontent.com/isabelroses/opera-gx/main/assets/latte.webp
https://raw.githubusercontent.com/isabelroses/opera-gx/main/assets/frappe.webp
https://raw.githubusercontent.com/isabelroses/opera-gx/main/assets/macchiato.webp
https://raw.githubusercontent.com/isabelroses/opera-gx/main/assets/mocha.webp

### Any additional comments?

Opera GX is windows only. (ignoring wine and other emulation forms)
GX mods requires a light and dark mode, so all the the dark themes also come with latte.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hiya 👋 

I've tried out the port it and looks really good! Thanks for your work! <3

Just some things to point out are some mistakes in the README:
- [I think you're missing a word here](https://github.com/isabelroses/opera-gx/blob/e36089be9d813b234f074b8bdf1793ac364fda29/README.md?plain=1#L40) - Makes more sense if it was `Download GX Mods from the`
- [Should be Opera, not Oprea](https://github.com/isabelroses/opera-gx/blob/e36089be9d813b234f074b8bdf1793ac364fda29/README.md?plain=1#L4)
- [Again, should be Opera and not Oprea](https://github.com/isabelroses/opera-gx/blob/e36089be9d813b234f074b8bdf1793ac364fda29/README.md?plain=1#L45)

Other than that, It would be really good if there was a GitHub Actions workflow to distribute the `.crx` files via releases so that it's easier to download!

Anyways, please fix the above mistakes and feel free to transfer it over! We'll close it off once it's added to the ports.yml that you're quite familiar with :P
