### ISSUE TITLE
Asciinema

### ISSUE THREAD

**Issue by mbekkomo** [catppuccin/catppuccin#2104]
### Link to repository

https://github.com/cattokomo/catppuccin-asciinema

### Screenshots

![preview](https://github.com/cattokomo/catppuccin-asciinema/raw/main/assets/preview.webp)
![latte](https://github.com/cattokomo/catppuccin-asciinema/raw/main/assets/latte.webp)
![frappe](https://github.com/cattokomo/catppuccin-asciinema/raw/main/assets/frappe.webp)
![macchiato](https://github.com/cattokomo/catppuccin-asciinema/raw/main/assets/macchiato.webp)
![mocha](https://github.com/cattokomo/catppuccin-asciinema/raw/main/assets/mocha.webp)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hey, thanks for your patience with this one! we were debating its utility given that it couldn't be used in the web player yet. it looks like the asciinema team has made some [really nice improvements](https://github.com/asciinema/asciinema/pull/617) in prep for the v3 release, however since that release is not out yet i'm inclined to say this port still adds value.

if you are still interested in maintaining this repo @cattokomo then i think we can work towards getting it added to the org. i notice you've changed your name since opening this port request - if you'd like to update your name in the "thanks to" section of the readme then now is the time!

**Comment by cattokomo** [comment]
The "Thanks to" section has been updated in commit cattokomo/catppuccin-asciinema@f631757
