### ISSUE TITLE
Chroma (Syntax Highlighter) / Hugo Syntax Highlighting

### ISSUE THREAD

**Issue by icy-comet** [catppuccin/catppuccin#2110]
### Link to repository

https://github.com/icy-comet/catppuccin-chroma-theme/

### Mocha
![mocha](https://github.com/catppuccin/catppuccin/assets/50461557/1d3f1179-ebcf-463b-a37c-8692f2e57644)

### Macchiato
![macchiato](https://github.com/catppuccin/catppuccin/assets/50461557/83bb467e-a521-4bca-a15e-1c4b837ad240)

### Frappe
![frappe](https://github.com/catppuccin/catppuccin/assets/50461557/f9e9c32a-3f40-4a3e-8762-31fd1e05e664)

### Latte
![latte](https://github.com/catppuccin/catppuccin/assets/50461557/24e949fb-c003-461f-9029-45b16eb86aef)

### Any additional comments?

This port creates both XML as well as CSS styles for the Chroma Syntax Highlighter. So, this is also useful for Hugo users.

What makes this different than the already merged styles in Chroma?
This makes sure the Chroma styles remain up-to-date with the changes in the color pallete, if any, since the styles are dynamically generated through a script.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave: @icy-comet
Firstly, let me apologise for how its taken to get around to this! 

Thank you for creating this port, I know that @jolheiser was able to take this upstream directly into chroma itself, which is great!

I'm more than happy having a `catppuccin/chroma` repository as well as the upstreamed version in chroma itself, as it would allow us to make tweaks at our own pace instead of relying on external people. Currently, the syntax highlighting both in this repository and upstream is slightly misaligned with our new style guide but we can iterate towards this!

I'm happy for this repository to be transferred into the organisation. I know that it's been a while since the issue was raised so I'd like to confirm if you are still interested in maintaining/collaborating with Catppuccin. No pressure if you are unable to / don't want to! I believe @jolheiser would be interested in either collaborating with yourself or creating another repository for transfer. 

Let me know what you think!

**Comment by icy-comet** [comment]
> Currently, the syntax highlighting both in this repository and upstream is slightly misaligned with our new style guide but we can iterate towards this!

I love the colorscheme. So yeah, let me know the necessary changes and we can get it fixed.

**Comment by sgoudham** [comment]
Great! @icy-comet I'm sure @jolheiser would be interested in helping out too.

A few minor comments about the repository:

1. Please update the [LICENSE](https://github.com/icy-comet/catppuccin-chroma-theme/blob/2eed1a3412bdd7e4677111e5ec5d9c4bde44b47e/LICENSE#L3) to match our [template](https://github.com/catppuccin/template/blob/4335bca70b2cc4b8bdd1b51164005207f46aeff6/LICENSE#L3).
2. Please update the [assets]() to be `.webp`, you can find more information on how to do this at https://github.com/catppuccin/userstyles/blob/main/docs/tips-and-tricks.md#how-do-i-convert-preview-images-to-webp.
3. Please update the [README badges](https://github.com/icy-comet/catppuccin-chroma-theme/blob/2eed1a3412bdd7e4677111e5ec5d9c4bde44b47e/README.md?plain=1#L8-L12) to be `catppuccin/chroma` instead of `icy-comet/catppuccin-chroma-theme`.
4. I think the [Use with]() section could be simplified to the following:

	```md
	## Usage
	
	### Chroma CLI

	#### CSS Styles
		- Specify the output format as `html` when invoking `chroma` with `chroma -f html`.
		- Clear out the styles from the generated output, i.e. delete everything in between the opening and closing `<style>` tags.
		- Then just copy and paste the contents of `dist/{flavor}-chroma-style.css` in the cleared space.
		- You might need to adjust the body's text and background color yourself.

	#### XML Styles
		- Specify the path (on your device) to the `dist/{flavor}-chroma-style.xml` when invoking `chroma` with the `-s` flag.

	### Hugo 🛠️
		- Set `markup.highlight.noClasses` to `false` in your Hugo config.
		- Include the desired stylesheet — `dist/{flavor}-chroma-style.css` in your layouts, e.g. in a `head` partial to make it available on all pages.
	```

The above comments are pretty minor and I'm happy to raise style guide issues once the port is under the organisation so lets get this transferred as `catppuccin/chroma`!

 Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by icy-comet** [comment]
I did the necessary.

Now, how do I initiate the transfer process? Transferring to the `catppuccin` org raises this error:
```
You don’t have the permission to create public repositories on catppuccin.
```

**Comment by sgoudham** [comment]
> You don’t have the permission to create public repositories on catppuccin.

You should have an invite to the organisation pending in your inbox of the email address you use for your GitHub account, try transferring the repository after accepting the invite!

**Comment by icy-comet** [comment]
Transfer complete.

**Comment by uncenter** [comment]
> Transfer complete.

Last step is for you to make a PR adding the port to [`ports.yml`](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml) (e.g. https://github.com/catppuccin/catppuccin/pull/2317) btw.
