### ISSUE TITLE
Halloy

### ISSUE THREAD

**Issue by Daeraxa** [catppuccin/catppuccin#2111]
### Link to repository

https://github.com/Daeraxa/catppuccin-halloy.git

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/58074586/4a9d98ab-29b3-45c1-bc22-ef410546a357)

<details>
<summary>🌻 Latte</summary>
<img src="https://github.com/catppuccin/catppuccin/assets/58074586/5eaae0dd-ec98-49e6-a6c0-613099ab3067"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://github.com/catppuccin/catppuccin/assets/58074586/8465a865-1dd8-4828-be44-2474bbfe0729"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://github.com/catppuccin/catppuccin/assets/58074586/6cfed20b-5344-4535-b7de-90c4dcb81111"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://github.com/catppuccin/catppuccin/assets/58074586/8273cdf2-daaa-4345-b1c6-7f33bcd28b61"/>
</details>

### Any additional comments?

There will probably be a lot of changes to the way some of the theming works in the future from what I understand (I'm not affiliated with the Halloy project) so there may need to be quite a few updates but this is accurate as of now.

This is the first port I've tried to do for Catppuccin so I'm more than accepting of feedback to see if I've used the styles correctly or if there are improvements that can be made here.

The app does some of its own styling in places where it takes one colour and modifies it for a few different elements (such as the background colour which is one "base" colour but provides 4 or 5 different colours in the app).

I have a fork of halloy itself so I couldn't easily just make a `daeraxa/halloy` repo so I hope this is OK, otherwise I'll have to do some workarounds.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hi there! :wave: 
Thanks for working on this, and apologies for the wait in feedback!

First things first, don't worry about the naming of the repository. You're given a chance to rename the repository when transferring into different GitHub organisations :+1: 

I've installed the app and it looks great, great job with applying the palette! However, I've just got a few comments about the repository:

1. As per the [updated contributing guidelines](https://github.com/catppuccin/catppuccin/commit/e77d79907932dc38fbdd2468ab1a29fd98d15ba4), we prefer `.webp` files in the `assets` directory instead of `.png` files. It would be great if you could convert them!
2. In terms of the repository structure, I can see that there are only 4 yaml files that are needed but they're under folders anyways. I think it would much more sense to bring those files up to the root level of the repository. E.g.

	- `latte/latte.yaml` -> `catppuccin-latte.yaml`
	- `frappe/frappe.yaml` -> `catppuccin-frappe.yaml`
	- `macchiato/macchiato.yaml` -> `catppuccin-macchiato.yaml`
	- `mocha/mocha.yaml` -> `catppuccin-mocha.yaml`
	
	I think the files should also be named with `catppuccin-` preceding them as the `Usage` section in the README shows the key as `catppuccin-frappe`.
3. Misspelling of Catppuccin [here](https://github.com/Daeraxa/catppuccin-halloy/blob/b283cade1b51aeaf0817346f06aec0c76b22d26f/README.md?plain=1#L45), should be updated to `catppuccin-frappe`
4. This is just a slight nitpick but the bullet points in the README should be nested further so it's not at the same level as the numbered list! Additionally, we should make use of GitHub releases so that people can easily download all the theme files but that can be done later on!

I think we should be good to transfer after the above points are addressed. I'm happy to clarify any points that may be hard to understand! 

Thanks again for working on this!

**Comment by Daeraxa** [comment]
Thanks for reviewing!

1. `.png` converted to `.webp`
2. Theme files renamed and moved up a level
3. Typo corrected
4. Badges updated to `catppuccin/halloy` (obviously won't be correct just yet)
5. Bullets indented (I did have a two space indent but apparently GH needs 4 to actually do it).

I also agree about the releases but makes sense to do this if/when it is moved to the main repo.

**Comment by sgoudham** [comment]
Thank you for updating as per the review comments!

One very minor thing is that the images are still looking for `*.png` files in the README so they'll need to be updated to use `*.webp` [here](https://github.com/Daeraxa/catppuccin-halloy/blob/13e3f12a3258aee9d281e1e068cd82959739155b/README.md?plain=1#L20-L35)

I'm happy to make the edits to the README as above so I won't block the transfer based on that! You should receive an invite to the organisation shortly via email! You can follow GitHub's documentation on [how to transfer a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), and as mentioned previously, you'll want to update the name to just `halloy`!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!** You can find an example [here](https://github.com/catppuccin/catppuccin/pull/2132) of a port being added to the yaml.

**Comment by Daeraxa** [comment]
Should all be done now, I edited the image references (missed those as they were collapsed :smile:). Repo transferred (as just `halloy`) and PR for ports.yml raised.
