### ISSUE TITLE
aseprite

### ISSUE THREAD

**Issue by sofycat** [catppuccin/catppuccin#2126]
### Link to repository

https://github.com/sofycat/aseprite

### Screenshots

![AllPreview](https://github.com/catppuccin/catppuccin/assets/104361176/03a6aad9-4a34-435f-ab4a-b68fd3d110e7)
![FrappePreview](https://github.com/catppuccin/catppuccin/assets/104361176/29f52135-d0ca-4283-9ce6-674433a768d1)
![LattePreview](https://github.com/catppuccin/catppuccin/assets/104361176/ecde6cb9-856c-4fac-a88e-e466f8f8ef25)
![MacchiatoPreview](https://github.com/catppuccin/catppuccin/assets/104361176/2c47b8d4-8f2f-4cc5-9383-df69bcc82c2e)
![MochaPreview](https://github.com/catppuccin/catppuccin/assets/104361176/0956adf2-66eb-404f-9099-7de0dd3c0104)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hi :wave: 
Thanks for your work on this! I just have a few things regarding the repository (honestly kinda nitpicky sorry!):

1. I've noticed that the [general preview image](https://github.com/sofycat/aseprite/blob/main/assets/AllPreview.png) has vertical bars instead of our diagonal ones generated by [catwalk](https://github.com/catppuccin/toolbox#-catwalk). 
	As per our [contributing guidelines](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md#styling), please use the catwalk tool to generate the preview image, It makes sure the screenshots are consistent across the entire organisation!

2. The [FAQ section](https://github.com/sofycat/aseprite/blob/main/README.md#-faq) of the README should be removed as it's not relevant information for the user anymore.

3. It's not currently mentioned in our contributing guidelines but we do prefer `webp` images in the `assets/` folder of the repository as they take up less space compared to `png`. It would be great if you could convert the [existing `*.png` files](https://github.com/sofycat/aseprite/tree/main/assets) into `*.webp`

We should be fine to transfer into the organisation after the above points are addressed, thanks once again!

**Comment by sofycat** [comment]
> Hi 👋 Thanks for your work on this! I just have a few things regarding the repository (honestly kinda nitpicky sorry!):
> 
>     1. I've noticed that the [general preview image](https://github.com/sofycat/aseprite/blob/main/assets/AllPreview.png) has vertical bars instead of our diagonal ones generated by [catwalk](https://github.com/catppuccin/toolbox#-catwalk).
>        As per our [contributing guidelines](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md#styling), please use the catwalk tool to generate the preview image, It makes sure the screenshots are consistent across the entire organisation!
> 
>     2. The [FAQ section](https://github.com/sofycat/aseprite/blob/main/README.md#-faq) of the README should be removed as it's not relevant information for the user anymore.
> 
>     3. It's not currently mentioned in our contributing guidelines but we do prefer `webp` images in the `assets/` folder of the repository as they take up less space compared to `png`. It would be great if you could convert the [existing `*.png` files](https://github.com/sofycat/aseprite/tree/main/assets) into `*.webp`
> 
> 
> We should be fine to transfer into the organisation after the above points are addressed, thanks once again!

done! :) https://github.com/sofycat/aseprite

**Comment by sgoudham** [comment]
Have discussed the port on discord and made some PRs, happy for it to be transferred now 🎉 

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**
