### ISSUE TITLE
Rio Support

### ISSUE THREAD

**Issue by Brianalmeida** [catppuccin/catppuccin#2138]
### Link to repository

https://github.com/Brianalmeida/rio-theme

### Screenshots

[Frappe](https://github.com/Brianalmeida/rio-theme/blob/main/assets/frapp%C3%A9.webp)
[Latte](https://github.com/Brianalmeida/rio-theme/blob/main/assets/latte.webp)
[Macchiato](https://github.com/Brianalmeida/rio-theme/blob/main/assets/macchiato.webp)
[Mocha](https://github.com/Brianalmeida/rio-theme/blob/main/assets/mocha.webp)

### Any additional comments?

Link to the GitHub repo: https://github.com/raphamorim/rio

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hey, thanks for your contribution! i assume you meant to link [rio-theme](https://github.com/Brianalmeida/rio-theme) rather than your fork of rio itself.

i've tested the theme and it all seems to work as i'd expect. just a couple of changes on the repo itself if you don't mind:

- the main preview image can be generated with [`catwalk`](https://github.com/catppuccin/toolbox?tab=readme-ov-file#-catwalk). i have generated one and attached it below, however i had to use the stacked layout as the four flavour previews you provided are of different sizes and positions. i think this looks fine, but if you'd like the usual sliced preview image then you'll need to recreate your flavour previews so they all line up with each other.
- the `config` link in the usage section of the readme ("Here is a example [config](https://raphamorim.io/rio/docs/)") is currently broken.

with those issues resolved, i'd be happy to accept this port into the org.

<hr>

![res](https://github.com/catppuccin/catppuccin/assets/289746/c1135f19-3069-402f-bbdb-874b54d70492)
if you do want to use this image, it'll need to be converted to webp (gh embed apparently doesn't support it!)

**Comment by Brianalmeida** [comment]
Hey @backwardspy, thanks for reviewing this port. I went ahead and made the changes that you pointed out. Please let me know if there is anything else that needs improvement.

**Comment by backwardspy** [comment]
@sgoudham ready for org invite and transfer

**Comment by sgoudham** [comment]
Thanks @Brianalmeida for your work! I've invited you to the organisation.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by Brianalmeida** [comment]
@sgoudham should I make a PR to add this to the port.yml file?

**Comment by sgoudham** [comment]
Sorry I should have been more clear in my previous comment @Brianalmeida, the process of transferring the repository to another organisation is listed [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account).

The PR should be raised once the repository has been transferred :+1:
