### ISSUE TITLE
SimpleX

### ISSUE THREAD

**Issue by iruzo** [catppuccin/catppuccin#2144]
### Link to repository

https://github.com/iruzo/simplex

### Screenshots

<img src="https://raw.githubusercontent.com/iruzo/simplex/main/assets/preview.webp"/>

<details>
<summary>🌻 Latte</summary>
<img src="https://raw.githubusercontent.com/iruzo/simplex/main/assets/simplex-latte.png"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://raw.githubusercontent.com/iruzo/simplex/main/assets/simplex-frappe.png"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://raw.githubusercontent.com/iruzo/simplex/main/assets/simplex-macchiato.png"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://raw.githubusercontent.com/iruzo/simplex/main/assets/simplex-mocha.png"/>
</details>

### Any additional comments?

I would appreciate some help to test this port, specially with `latte` before porting it.
Every flavor except `latte` is pretty well tested.

Thanks in advance !

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
thanks for your contribution! the port looks really nice.

i only found one issue; on latte several ui text elements are white which, against the light background, makes them almost unreadable:

![image](https://github.com/catppuccin/catppuccin/assets/289746/6bd579fd-c804-4a32-9ff1-5075a975b503)
![image](https://github.com/catppuccin/catppuccin/assets/289746/99aeab51-48fb-4b26-b029-c1bf4b9a1f0c)

i think once that's fixed we could get this port transferred.

**Comment by kremzli** [comment]
That issue should be fixed with this https://github.com/simplex-chat/simplex-chat/pull/3635

**Comment by iruzo** [comment]
I have tried v5.5 on Android and no luck with latte.

**Comment by kremzli** [comment]
Look through here https://github.com/simplex-chat/simplex-chat/issues/3363 the theme now needs to change the colors of the chat bubbles. Then it all should be good

**Comment by iruzo** [comment]
Fix have been pushed to the repo.
@sgoudham the PR is ready so whenever you have time to check it, I can transfer the port. As soon as the repo is transferred, I will open the PR to modify ports.yml.

**Comment by sgoudham** [comment]
Hey @iruzo, thanks for pushing that fix! I'll take you up on your word that the fix is correctly working :D (thanks also to @kremzli for following up on simplex itself!)

I've got a few minor comments about the codebase:

1. Please convert all `*.png` files to `*.webp` in the [assets](https://github.com/iruzo/simplex/tree/main/assets) directory. (you can technically remove the `.gitkeep` file too)
2. Please convert the [README image urls](https://github.com/iruzo/simplex/blob/263ed4ff076f2b8811878ebd0eca63c0dd1acae8/README.md?plain=1#L14-L35) to be [relative urls](https://github.blog/2013-01-31-relative-links-in-markup-files/).
3. Consider using [whiskers](https://github.com/catppuccin/toolbox/tree/main/whiskers#readme) in the future to generate this port as this repository is a perfect use case for it.

My comments above are pretty minor and can be fixed easily so I'm happy to approve this for transfer into the organisation! Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164

**Comment by iruzo** [comment]
@sgoudham Port has been moved to the org and all changes have been done. [I already created the PR for the `ports.yml` file](https://github.com/catppuccin/catppuccin/pull/2266).
@kremzli I hope you don't mind if I add you to the "Thanks to" section :wink:
