### ISSUE TITLE
Sioyek

### ISSUE THREAD

**Issue by 21st-centuryman** [catppuccin/catppuccin#2166]
### Link to repository

https://github.com/21st-centuryman/Sioyek

### Screenshots

<img width="888" alt="Screenshot 2023-09-17 at 01 00 48" src="https://github.com/catppuccin/catppuccin/assets/60197499/8151f89f-8297-4b4c-a850-d877cf05ef3f">
<img width="898" alt="Screenshot 2023-09-17 at 01 03 48" src="https://github.com/catppuccin/catppuccin/assets/60197499/da80be21-3249-4b2c-a2cb-22dd0a06abf8">
<img width="902" alt="Screenshot 2023-09-17 at 01 04 14" src="https://github.com/catppuccin/catppuccin/assets/60197499/17466ccd-48bf-4e4d-8a62-c8cc2795f619">
<img width="902" alt="Screenshot 2023-09-17 at 01 04 41" src="https://github.com/catppuccin/catppuccin/assets/60197499/db1414a7-d159-4cb9-be2a-f9a0e410967c">

### Any additional comments?

Pdfs are not really known for their color full nature, but I have followed the guide to a t and manage to test it.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by quantumfate** [comment]
I need this. Thank you so much for the port

**Comment by sgoudham** [comment]
Hey :wave:, apologies for the wait!

I briefly tried this out and can confirm that it works, nice job! I did find that the app was quite buggy but I don't think that's the fault of the theme.

Just one tiny change from me, all of the [themes](https://github.com/21st-centuryman/Sioyek/tree/main/themes) have an incorrect header `CATPPUCCI` instead of `CATPPUCCIN`. Would be greatly appreciated if you could just update that! Since this change is so minor (and can be easily updated after the port has been transferred) - I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164

**Comment by 21st-centuryman** [comment]
Hello, 

thank you for your comment, I will start the transfer process right away

**Comment by 21st-centuryman** [comment]
I believe everything has been done @sgoudham
