### ISSUE TITLE
VSCode Peacock

### ISSUE THREAD

**Issue by repraze** [catppuccin/catppuccin#2208]
### Link to repository

https://github.com/repraze/catppuccin-vscode-peacock

### Screenshots

![preview](https://raw.githubusercontent.com/repraze/catppuccin-vscode-peacock/main/assets/preview.webp)

### Any additional comments?

The repo contains the palette as favorite colors for the VSCode Peacock extension.
The repo name has `catppuccin-` as a placeholder and can be renamed before/after moving.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nullishamy** [comment]
Probably shouldn't commit `node_modules`

https://github.com/repraze/catppuccin-vscode-peacock/blob/main/assets/.gitkeep Can be deleted

Other than that, looks good to me!

**Comment by sgoudham** [comment]
Hey :wave:

Instead of creating a separate repository for a VSCode extension, I believe it would be much better to integrate this work directly into our existing https://github.com/catppuccin/vscode port.

There are already some extensions defined in the https://github.com/catppuccin/vscode/tree/main/src/theme/extensions directory which, to my knowledge, would be perfectly suitable for the theming provided in this repository. 

Please also see an example PR: https://github.com/catppuccin/vscode/pull/216 on the general structure on how to add support for an extension.

I'll close this issue but please feel free to re-open this if you still feel like this should be a standalone repository, thanks for your work!

**Comment by repraze** [comment]
Got it! I'll check it out

**Comment by repraze** [comment]
I don't think the plugin is themable through the vscode theme since peacock uses `configuration` to store favorite colors and does not contribute any `colors` for the theme to swap.

I opened an issue on the vscode theme plugin, but I doubt it can be supported.

**Comment by InvitedToHell** [comment]
Any progress on this? @repraze

**Comment by repraze** [comment]
> Any progress on this? @repraze 

No progress since the vscode plugin doesn't support it. A lot of rework of the internals of the plugin is needed. My original repo/submission is still the best option.

**Comment by InvitedToHell** [comment]
Alright! Thanks a lot for the repo!
