### ISSUE TITLE
Forklift 4

### ISSUE THREAD

**Issue by denis-g** [catppuccin/catppuccin#2241]
### Link to repository

https://github.com/denis-g/theme-forklift4-catppuccin

### Screenshots

<img src="https://raw.githubusercontent.com/denis-g/theme-forklift4-catppuccin/master/assets/previews/preview.webp" />

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hi @denis-g, just tried this out earlier - looks great! 

I just had a few comments from my end:

1. Not necessarily related to the theme but could I ask how you exported the themes from forklift into the command line string? I couldn't find any settings / documentation on the website on how to do that. (I really hope you didn't manually write the command in the Usage section yourself :sweat_smile:)
2. I know our style guide does list that crust can be used for secondary panels / sidebars but I personally would like the sidebar here to be `mantle` instead of `crust`, and we don't typically use the `base` colour as the selection background but one of the `surface` colours instead.

	For example, here is the sidebar in our VSCode theme:
	![image](https://github.com/catppuccin/catppuccin/assets/58985301/9800e92d-72ab-460b-b161-375676100e49)
	
	Following the above, I would set the sidebar background to `mantle` and set the selection background to `surface0`, here's what that would look like:
	
	(Latte) - sidebar as `mantle` and selection as `surface0`
	<img width="199" alt="image" src="https://github.com/catppuccin/catppuccin/assets/58985301/399aae11-8743-4137-99ad-214f5d41659b">

		
	(Mocha) - sidebar as `mantle` and selection as `surface0`
	<img width="198" alt="image" src="https://github.com/catppuccin/catppuccin/assets/58985301/6a8b70c3-dce9-489c-810c-c64594f3eb7b">
	
	I think these match our existing conventions much better and I'd appreciate if you could make that change across all four flavours!
	
I think once `2.` is implemented, we should be good to move it into the organisation!

**Comment by denis-g** [comment]
Hi,

1. Yep :) The app does not support settings export and saved this in the macOS native `.pllist` configuration file.
To view user custom themes in plain text (by default saved in base64):
```shell
/usr/libexec/PlistBuddy -c 'print ":themes"' ~/Library/Preferences/com.binarynights.ForkLift.plist
```
2. I'm updated repo with corrected colors.

**Comment by sgoudham** [comment]
Nice, thanks for changing the colours!

Just some things in the README that I also noticed just now:

1. The [README badge links](https://github.com/denis-g/theme-forklift4-catppuccin/blob/f01997ec568997e589fcab2cccb7ba327c10432c/README.md?plain=1#L8-L12) should be updated to pointed towards `catppuccin/forklift-4` instead of `catppuccin/template`
2. The [README asset preview links](https://github.com/denis-g/theme-forklift4-catppuccin/blob/f01997ec568997e589fcab2cccb7ba327c10432c/README.md?plain=1#L14-L35) should be updated to use relative markdown links.

But the above are minor things can be fixed easily upon transfer, so I'm happy to approve this port for transfer!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164
