### ISSUE TITLE
Fuzzel

### ISSUE THREAD

**Issue by tetov** [catppuccin/catppuccin#2243]
### Link to repository

https://github.com/tetov/ctp-fuzzel

### Screenshots

![](https://raw.githubusercontent.com/tetov/ctp-fuzzel/main/assets/preview.webp)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Heya :wave:, got some members in our discord using Wayland to test this out - it looks good!

Just one tiny comment from me: 

The README incorrectly refers to configuration locations with `foot` instead of `fuzzel`, please replace each occurrence of `foot` with `fuzzel`.

After the README is fixed, I'd be happy to approve this for transfer into the organisation! (also thank you for using `whiskers` while it's still not officially advertised anywhere, this type of repository is the perfect usecase for that tool!)

**Comment by tetov** [comment]
Thanks for your review!

Sorry for the oversight, the usage docs are now referring to fuzzel's config file not foot's. :)

(https://github.com/tetov/ctp-fuzzel/commit/9aa88c2bd00b0b0c3fc7f0d713f9c2dbf118e552)

**Comment by sgoudham** [comment]
Thanks! Hilariously I've just found 2 more issues

1. The paths configured in the [README](https://github.com/tetov/ctp-fuzzel/blob/9aa88c2bd00b0b0c3fc7f0d713f9c2dbf118e552/README.md?plain=1#L14-L35) are incorrectly pointing to `assets/preview` when the images don't exist in that folder anymore. Also, the preview image should be converted to a relative link too.
2. Catppuccin is spelled incorrectly in the [README badges](https://github.com/tetov/ctp-fuzzel/blob/9aa88c2bd00b0b0c3fc7f0d713f9c2dbf118e552/README.md?plain=1#L9-L11).

Should be good to transfer after these are fixed :D

**Comment by tetov** [comment]
Hi!

Fixed. Not sure how the misspelling got in there.

**Comment by sgoudham** [comment]
Thanks! I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164
