### ISSUE TITLE
swaylock

### ISSUE THREAD

**Issue by remiposo** [catppuccin/catppuccin#2248]
### Link to repository

https://github.com/remiposo/swaylock

### Screenshots

<img src="https://raw.githubusercontent.com/remiposo/swaylock/main/assets/preview.webp">

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:, thanks for submitting this!

@isabelroses kindly reviewed the theme on my behalf and it looks great - thank you for your work on this!

I just have a few nitpicks/comments about the repository:

1. Our repository conventions are to use `*.webp` for the asset preview images, please update all images in the [assets folder](https://github.com/remiposo/swaylock/tree/main/assets) to be `.webp` 

> [!TIP]
> If you're on unix, an easy command for converting is something like 
> ```
> for i in latte frappe macchiato mocha; convert "$i.png" -quality 100 "$i.webp"; end
> ```

2. The `Thanks to` section in the [README](https://github.com/remiposo/swaylock/blob/34c83919aed2d61430af00a6dec5844eda4514a4/README.md?plain=1#L44-L46) doesn't format the contributors with a list, please add a bullet pointed list here!

---

I'm happy to approve the transfer of this theme into the organisation since my comments don't actually affect the user's experience in downloading / using the theme, and can be updated pretty easily afterwards too. 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164

**Comment by isabelroses** [comment]
> Tip
> 
> If you're on unix, an easy command for converting is something like
> 
> ```
> for i in latte frappe macchiato mocha; convert "$i.png" -quality 100 "$i.webp"; end
> ```

Just a bit to add to this you need [imagemagick](https://imagemagick.org/index.php) for the `convert` command to work.

**Comment by remiposo** [comment]
@sgoudham 

Thank you for your comments!!
I believe everything has been done.
