### ISSUE TITLE
fr33zmenu

### ISSUE THREAD

**Issue by iruzo** [catppuccin/catppuccin#2276]
### Link to repository

https://github.com/iruzo/fr33zmenu

### Screenshots

<p align="center">
	<img src="https://raw.githubusercontent.com/iruzo/fr33zmenu/main/assets/preview.webp"/>
</p>

## Previews

<details>
<summary>🌻 Latte</summary>
<img src="https://raw.githubusercontent.com/iruzo/fr33zmenu/main/assets/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://raw.githubusercontent.com/iruzo/fr33zmenu/main/assets/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://raw.githubusercontent.com/iruzo/fr33zmenu/main/assets/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://raw.githubusercontent.com/iruzo/fr33zmenu/main/assets/mocha.webp"/>
</details>

### Any additional comments?

Port should be ready to be transferred.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nullishamy** [comment]
Hiya

Overall, looks good! Only a few things to amend:
1) Your repo has `.yaml` files that actually contain `TOML`.
2) The installation guide is not terribly clear. It should make it more clear that you have to manually merge the theme into your config, rather than simply placing the file in the specified location.
3) These configs are not generated with a script. If possible, we'd prefer this, though it is not a deal breaker.

**Comment by iruzo** [comment]
Hi !

1. Oops, true, done!
2. Ty for noticing, done!
3. I created this port really fast since it is one of those simple apps with really simple configs. If it is really necessary I can take the time to change it.

**Comment by sgoudham** [comment]
I think its fine to revisit the repository for generating with whiskers, once that's more defined. 

Just two things from me:

1. I'd add a note into the `Usage` saying that the default theme provided by application is already Catppuccin Mocha, so they don't need to copy it over.
2. Regenerate the previews with a much bigger font size since 80% of the current preview is the terminal and not the application itself.

Should be good to transfer after the above changes have been carried out!

**Comment by iruzo** [comment]
@sgoudham 

1. Done
2. Done

Thanks for the feedback !

**Comment by sgoudham** [comment]
Thanks, I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
