### ISSUE TITLE
Yazi

### ISSUE THREAD

**Issue by uncenter** [catppuccin/catppuccin#2278]
### Link to repository

https://github.com/uncenter/ctp-yazi

### Screenshots

<p align="center">
	<img src="https://github.com/uncenter/ctp-yazi/raw/main/assets/previews/preview.webp"/>
</p>

## Previews

<details>
<summary>🌻 Latte</summary>
<img src="https://github.com/uncenter/ctp-yazi/raw/main/assets/previews/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://github.com/uncenter/ctp-yazi/raw/main/assets/previews/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://github.com/uncenter/ctp-yazi/raw/main/assets/previews/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://github.com/uncenter/ctp-yazi/raw/main/assets/previews/mocha.webp"/>
</details>

### Any additional comments?

Closes https://github.com/catppuccin/catppuccin/discussions/2189.

### Submission Guidelines

- [x] I have read and followed Catppuccin's submission guidelines.

**Comment by sxyazi** [comment]
Thanks! Could we have a separate directory for each theme and add the tmTheme files to them? Like this:

```
.
├── frappe
│   ├── Catppuccin-frappe.tmTheme
│   ├── LICENSE
│   ├── screenshot.png
│   └── theme.toml
├── latte
│   ├── Catppuccin-latte.tmTheme
│   ├── LICENSE
│   ├── screenshot.png
│   └── theme.toml
├── macchiato
│   ├── Catppuccin-macchiato.tmTheme
│   ├── LICENSE
│   ├── screenshot.png
│   └── theme.toml
└── mocha
    ├── Catppuccin-mocha.tmTheme
    ├── LICENSE
    ├── screenshot.png
    └── theme.toml

5 directories, 16 files
```

**Comment by uncenter** [comment]
> Thanks! Could we have a separate directory for each theme and add the tmTheme files to them? Like this:
> 
> ```
> .
> ├── frappe
> │   ├── Catppuccin-frappe.tmTheme
> │   ├── LICENSE
> │   ├── screenshot.png
> │   └── theme.toml
> ├── latte
> │   ├── Catppuccin-latte.tmTheme
> │   ├── LICENSE
> │   ├── screenshot.png
> │   └── theme.toml
> ├── macchiato
> │   ├── Catppuccin-macchiato.tmTheme
> │   ├── LICENSE
> │   ├── screenshot.png
> │   └── theme.toml
> └── mocha
>     ├── Catppuccin-mocha.tmTheme
>     ├── LICENSE
>     ├── screenshot.png
>     └── theme.toml
> 
> 5 directories, 16 files
> ```

I think the duplication of files isn't ideal. I'm guessing most users will want the correct, matching syntax highlighting as you said but even more people could possibly already be using catppuccin/bat and it might be confusing if they don't realize the `tmTheme` files are identical to what they already have.

**Comment by sxyazi** [comment]
> but even more people could possibly already be using catppuccin/bat and it might be confusing if they don't realize the tmTheme files are identical to what they already have

Yazi and `bat` are two independent programs, and `bat` is not a dependency of Yazi. They both just happen to use the same Rust highlighter, [syntect](https://github.com/trishume/syntect).

I don't think it makes sense to not add them to Yazi just because users already have `bat` installed and have `bat`'s syntect theme files.

**Comment by sgoudham** [comment]
Hey :wave:, thanks for porting the code over to whiskers @uncenter, and @sxyazi for originally implementing the theme!

> Thanks! Could we have a separate directory for each theme and add the tmTheme files to them? Like this:

Separate directories aren't inherently a bad idea, however, it doesn't follow our project layout conventions which we follow across >250 repositories (and duplicating the LICENSE file doesn't make much sense to me here)

> I think the duplication of files isn't ideal. I'm guessing most users will want the correct, matching syntax highlighting as you said but even more people could possibly already be using catppuccin/bat and it might be confusing if they don't realize the tmTheme files are identical to what they already have. I'm curious what you think, @sgoudham?

Yeah, taking into consideration the scale of Catppuccin, I'd really like to avoid duplication. For the README, I think it's okay to link out to another repository and tell users to download file(s) from there. In this specific case, I'd move out the instructions from the **FAQ** into the **Usage** section so that its the next step. For example:

```md
## Usage

1. Copy the theme file of your choice from `themes/` to your [Yazi configuration directory](https://yazi-rs.github.io/docs/configuration/overview) with the filename `theme.toml`.
2. Download the `.tmTheme` file of your choice from [catppuccin/bat](https://github.com/catppuccin/bat).
	- Replace path of `syntect_theme` (line 27) to the path of your downloaded `.tmTheme` file.
```

It's worth mentioning that [catppuccin/bat](https://github.com/catppuccin/bat)'s `.tmTheme` files are in need of a rework to better align with the syntax highlighting guidelines introduced over the last year, and an update to those files should be expected soon :tm:

I'd appreciate if you could move the FAQ into the Usage section as outlined above :+1: @uncenter

**Comment by uncenter** [comment]
> I'd appreciate if you could move the FAQ into the Usage section as outlined above 👍 @uncenter

[Done!](https://github.com/uncenter/ctp-yazi#usage) I added a short explanation of why the `.tmTheme` file is necessary, I think it works fine but let me know if it needs further adjustment.

**Comment by sgoudham** [comment]
Yeah I think it's fine, my nitpick review would be to format it a little nicer, e.g.

```md
2. For Catppuccin-themed syntax highlighting in the preview pane: 
	- Download the `.tmTheme` file of your choice from [catppuccin/bat](https://github.com/catppuccin/bat)
	- Replace the path of `syntect_theme` (line 27) with the path of your downloaded `.tmTheme` file.
```

But it's not something I care too much about, and as you said, it's fine. 

Nice work on this, I'm happy for it to be transferred over to the organisation! (Can I quickly confirm that you are okay to be listed as the maintainer of this port? Or will it be @sxyazi ?)

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164

## Outstanding Actions After Transfer

- All Catppuccin code should be removed from the [yazi-rs/themes](https://github.com/yazi-rs/themes) repository.
- https://github.com/yazi-rs/themes/issues/3 should be closed as not planned.

**Comment by uncenter** [comment]
I'm happy to maintain it, yep!

**Comment by sxyazi** [comment]
@sgoudham OK, thanks for explaining.
Any chance I can convince you to add these `tmTheme` files and change the directory layout?

I will provide a more explicit definition in the theme-making documentation/template for Yazi in the next few days - A Yazi theme that does not include a `tmTheme` file is considered an **invalid** theme, and each theme **must** be in its own directory.

This not only eliminates the need for users to separately download and configure additional files/options, but also enables future theme managers to automate the process. All that will be required is to move the entire directory to `~/.config/yazi/themes`, without the need to analyze various `README` files to see if they contain another repository link pointing to a `tmTheme` file, and then download it, as the directory structure could be quite diverse.

**Comment by uncenter** [comment]
> A Yazi theme that does not include a `tmTheme` file is considered an **invalid** theme, and each theme **must** be a directory.

Hmm. At that point I question the merits of having two theme files if one is invalid without the other? Seems like they should be joined in some way?

> all that will be required is to move the entire directory to `~/.config/yazi/themes`

I'm confused since doesn't Yazi not support this kind of behavior? It looks for `~/.config/yazi/theme.toml`, not anything in the `themes` directory right? And this brings up the idea we discussed in Discord earlier regarding remote themes and caching them and all that...

**Comment by sxyazi** [comment]
> Hmm. At that point I question the merits of having two theme files if one is invalid without the other? Seems like they should be joined in some way?

I'm not quite sure I understand your meaning. Are the "two theme files" referring to the theme Yazi itself and the "tmTheme" file?

What I mean is that frappe, latte, macchiato, and mocha should be 4 different Yazi themes. Ideally, they should each be in their own repository (with files stored in the repository root, so you can think of it as a directory, similar to the structure of Yazi plugins, like https://github.com/dedukun/bookmarks.yazi).

However, it is acceptable for them to be in the same repository, but they should be in at least 4 different directories.

> I'm confused since doesn't Yazi not support this kind of behavior? It looks for ~/.config/yazi/theme.toml, not anything in the themes directory right? And this brings up the idea we discussed in Discord earlier regarding remote themes and caching them and all that...

“But also enables ***future*** theme managers to automate the process”

I've already mentioned, this is to prepare for the future and retain this flexibility for later expansion - I need to establish and push a theme structure, because changing the directory structure is a breaking change for the entire existing theme ecosystem, but fortunately, there are not many themes for Yazi at the moment.

As for the proposals you mentioned on Discord:

1. Adding a `themes` directory, the purpose is to allow Yazi to support multiple local themes and allow users to switch between them in the configuration.
2. Allowing loading network themes via URL, the purpose is to make theme updates more convenient, and by URL-izing tmTheme files, to address catppuccin's refusal to include them in Yazi themes.

These are two proposals with completely different purposes. I only rejected the second proposal, but added the first one to the roadmap for Yazi v0.3, and currently, this work is being prepared for it.
