### ISSUE TITLE
Hyprlock

### ISSUE THREAD

**Issue by NikSneMC** [catppuccin/catppuccin#2299]
### Link to repository

https://github.com/NikSneMC/hyprlock

### Screenshots

<p align="center">
	<img src="https://raw.githubusercontent.com/niksnemc/hyprlock/main/assets/preview.webp"/>
</p>

<details>
<summary>🌻 Latte</summary>
<img src="https://raw.githubusercontent.com/niksnemc/hyprlock/main/assets/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://raw.githubusercontent.com/niksnemc/hyprlock/main/assets/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://raw.githubusercontent.com/niksnemc/hyprlock/main/assets/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://raw.githubusercontent.com/niksnemc/hyprlock/main/assets/mocha.webp"/>
</details>

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
Hai, after taking a quick look can't we do something more similar to the [hyprland port](https://github.com/catppuccin/hyprland) instead of including a default config. Futhermore, why is there preview 1-4 in the assets, when only 1 is being used?

Other then that good work.

**Comment by sgoudham** [comment]
Also taking a quick look at the repository, it looks like the colour definitions are identical between `catppuccin/hyprland`  and here (which makes sense since its the same underlying config file)

I remember @backwardspy and I discussing the topic of how some of our repositories are essentially default personalised dotfile configurations. I think in this case, that's fine? Otherwise there wouldn't really be a port to begin with. 

I have a few comments:

1. Please remove the extra preview images, just the single `preview.webp` is fine.
2. Please convert the [README asset links](https://github.com/NikSneMC/hyprlock/blob/77476e6b641c683f066a1cfdde102b3a8206f045/README.md?plain=1#L14-L41) to be [relative urls](https://github.blog/2013-01-31-relative-links-in-markup-files/).
3. Please change the [default accent color]() to `mauve` as that is the convention we've settled on, I'll update the style guide to make this more explicit.
4. To make it seem less like you're cloning someone elses dotfiles, please use [Catppuccin's logo](https://github.com/catppuccin/catppuccin/blob/main/assets/logos/exports/macchiato_squircle.png) for the previews. I don't think we need to include the file itself in the repository as you've specified in the FAQ how to set the profile picture.

I'm not too fussed about the duplicated colour definitions as we'll have a unified tool in the future to automatically generate/update those. 

I think it should be good for transfer after the above changes have been implemented!

**Comment by backwardspy** [comment]
adding on to hammy's first point about the colours, how do you feel about this:

- remove the colour definition files and direct people to download them from [catppuccin/hyprland](https://github.com/catppuccin/hyprland).
- replace the four near-identical copies of `hyprlock.conf` with a single file and instruct users to change the `source` line at the top to the flavour they want.

this would help a lot with maintenance since any colour changes in the hyprland repo automatically apply here too, and any changes to `hyprlock.conf` only have to be done in one place.

let me know your thoughts!

**Comment by NikSneMC** [comment]
I've commited changes requested by @sgoudham and @backwardspy

**Comment by backwardspy** [comment]
i think that looks great! very cute design

**Comment by NikSneMC** [comment]
So, now I must wait for review, right?

**Comment by backwardspy** [comment]
looks like you've addressed everything so if @sgoudham is happy i'd say we're ready for an org invite

**Comment by sgoudham** [comment]
Nice job @NikSneMC! That looks great, thank you for implementing our suggestions.

I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2319
