### ISSUE TITLE
iSH

### ISSUE THREAD

**Issue by g3rhard** [catppuccin/catppuccin#2305]
### Link to repository

https://github.com/g3rhard/catppuccin-ish

### Screenshots

Could be found in repository: https://github.com/g3rhard/catppuccin-ish/tree/production/assets

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nullishamy** [comment]
Just tested this one out, it looks great! Only thing I'd note is that the install instructions are not super helpful at the minute. On my device, iSH refused to load from my Downloads folder. This can be avoided by cloning & installing the themes inside iSH itself, following their instructions. Here's roughly what I ran to install the themes:
```bash
$ mkdir ish-themes
$ mount -t real \"$(cat /proc/ish/documents)/themes\" ish-themes
$ git clone https://github.com/g3rhard/catppuccin-ish
$ cp catppuccin-ish/*.json ish-themes
```
Perhaps we could include these steps as a script?

**Comment by nullishamy** [comment]
Ah, I had a copying error in my example. The quotes for the second command shouldn't be escaped. I will just PR this once we get it into the org, no big deal. 

In any case, this looks good to merge!

**Comment by g3rhard** [comment]
Okay, what's my next steps?

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks to @nullishamy for testing it out.

Minor things about the README from me:
1. Consider changing the heading of `Installation instruction` to something more concise like `Usage` or `Installation`.
2. Add yourself to our [Thanks to](https://github.com/catppuccin/template#-thanks-to) section as defined in our template :D 

In any case, happy for it to be transferred into the organisation since they can be added afterwards. I've sent you an invite to join the organisation!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin. As per our port creation guidelines, please transfer the repository by keeping iSH lowercase -> `catppuccin/ish`.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
