### ISSUE TITLE
Catppuccin Startpage

### ISSUE THREAD

**Issue by pivoshenko** [catppuccin/catppuccin#2342]
### Link to repository

https://github.com/pivoshenko/catppuccin-startpage

### Screenshots

https://github.com/pivoshenko/catppuccin-startpage/assets/40499728/d96c8bd6-168e-408f-b4f0-0e339569c696

[Live demo](https://pivoshenko.github.io/catppuccin-startpage)

### Any additional comments?

Aesthetic and clean startpage in **Catppuccin** style, hosted on GitHub Pages.
So far there is only Mocha palette.

[dawn]: https://github.com/b-coimbra/dawn
[catppuccin]: https://github.com/catppuccin/catppuccin
[tartarus-startpage]:https://github.com/AllJavi/tartarus-startpage
[dotfiles]: https://github.com/pivoshenko/dotfiles

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nullishamy** [comment]
hi @pivoshenko, thanks for opening this!

as this is not a port, but rather an upload of a dotfile-esque startpage, we are inclined not to merge it into the org. we want ports to be more useful to a broader
audience, and to integrate well into other configurations. ports should act as building blocks rather than complete solutions.

with that said, our showcase on [catppuccin/catppuccin](https://github.com/catppuccin/catppuccin) is for exactly this! feel free to PR something into that if you like.
