### ISSUE TITLE
gh-dash

### ISSUE THREAD

**Issue by isabelroses** [catppuccin/catppuccin#2351]
### Link to repository

https://github.com/isabelroses/gh-dash

### Screenshots

![img](https://raw.githubusercontent.com/isabelroses/gh-dash/main/assets/preview.webp)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:, looks great and thanks for taking the time to create the repository!

Two comments from me: 

1. I think it'd be nicer to name the files as `catppuccin-<flavour>-<accent>.yml` instead of the `accent.yml`. Mostly because I think it's much more descriptive when downloading to the filesystem and saves the user having to rename it, and you also avoid rename popups/accidental overwrites if you're downloading files from multiple flavours. Let me know what you think.
2. We should honestly avoid the whole "Clone this repository" as a first step going forward lol, I'd keep the usage/installation section just your second bullet point about choosing and downloading a file from the themes directory.

In any case, they're minor comments so happy to approve!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
