### ISSUE TITLE
Calibre

### ISSUE THREAD

**Issue by 42Willow** [catppuccin/catppuccin#2367]
### Link to repository

https://github.com/42willow/calibre

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/70784752/13f031a9-749b-49b2-83b6-acc4d6730dfc)

### Any additional comments?

#1854 

First port :o

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by uncenter** [comment]
I wonder if it is worth theming the icons as well? Obviously not a priority but it would be neat. Looks like they are SVGs so hopefully not too difficult! I would be happy to do it if you don't have the time btw.

Here is the docs on it: https://manual.calibre-ebook.com/customize.html#creating-your-own-icon-theme-for-calibre.
Folder containing default icons: https://github.com/kovidgoyal/calibre/tree/master/imgsrc.

**Comment by 42Willow** [comment]
Ok, I'll give this a go. Do you know of any efficient method of doing this in batch either automatically or manually with inkscape?

**Comment by uncenter** [comment]
> Ok, I'll give this a go. Do you know of any efficient method of doing this in batch either automatically or manually with inkscape? If not that's fine, I've got a lot of clicking to do.

Hmm I mean I have a tool called `ctpvert` that attempts to find the closest Catppuccin color but for best results I would do it manually.

> Do you think it would better to retain the gradients in the icons or get rid of them?

I'm an favor of getting rid of the gradients :)

**Comment by sgoudham** [comment]
Hey :wave: 
Thanks for your work!

I've got a few comments:

1. I think it would be good to add the [`icons/dist`](https://github.com/42Willow/calibre/tree/main/icons/dist) folder to a `.gitignore` file as the icons are generated by a makefile and not needed in source control.
2. I feel like it'd be nicer to rename the theme files as `catppuccin-<flavour>-<accent>.calibre-palette` instead of just `<accent>.calibre-palette`. I know I'd much prefer downloading the former into my filesystem (and also prevents rename popups if you're downloading multiple accents/flavours)
3. The [`Base` key](https://github.com/42Willow/calibre/blob/80a2b3b4dda2c235f8f969d5d6725050258a3af4/calibre.tera#L20) should be set to `base` instead of `mantle` as I assume that this is the main background. For further details on how base/mantle should be used in accordance with our other ports, see [my comments on the Gitkraken issue](https://github.com/catppuccin/catppuccin/issues/2170#issuecomment-1890787340) (i.e main background as `base` and sidebars/sidepanels as `mantle`)

**Comment by sgoudham** [comment]
Discussed on discord with @42Willow, port looks good and thanks for implementing my above suggestions!

I'm happy for it to be transferred over to the organisation! Check your inbox for an invite to the Catppuccin GitHub organisation.

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
