### ISSUE TITLE
midnight

### ISSUE THREAD

**Issue by uncenter** [catppuccin/catppuccin#2388]
### Link to repository

https://github.com/uncenter/ctp-midnight

### Screenshots

<p align="center">
	<img src="https://github.com/uncenter/ctp-midnight/raw/main/assets/previews/preview.webp"/>
</p>

<details>
<summary>🌻 Latte</summary>
<img src="https://github.com/uncenter/ctp-midnight/raw/main/assets/previews/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://github.com/uncenter/ctp-midnight/raw/main/assets/previews/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://github.com/uncenter/ctp-midnight/raw/main/assets/previews/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://github.com/uncenter/ctp-midnight/raw/main/assets/previews/mocha.webp"/>
</details>

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by andreasgrafen** [comment]
I think this is mostly a Latte issue, but the sub menus can be hard to read depending on the content. especially timestamps and hover state are a bit iffy. Not sure *if* that's fixable since the base theme isn't supposed to be light-coloured, so the CSS might not allow for this. :/

<img width="552" alt="image" src="https://github.com/catppuccin/catppuccin/assets/35840154/9ec89694-506d-42dc-99fa-7c2ff17bd064">
