### ISSUE TITLE
VitePress

### ISSUE THREAD

**Issue by 42Willow** [catppuccin/catppuccin#2419]
### Link to repository

https://github.com/42willow/vitepress

### Screenshots

![](https://raw.githubusercontent.com/42willow/vitepress/main/assets/previews/preview.webp)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by uncenter** [comment]
We should probably figure out how to publish each flavor as a section/directory of an NPM package so you can just install it and import it instead of copying in a directory (the latter of which won't let you receive updates either).

**Comment by 42Willow** [comment]
Good idea

- [ ] npm packages
- [ ] justfile
- [ ] demo site

**Comment by sgoudham** [comment]
Hey :wave: 
Sorry for the wait on this one.

I have a couple questions about the port/codebase:

1. Can we add a section on the FAQ on why Latte isn't included? I'm assuming this is because of a technical limitation of some sort? I can't think of any reason why Latte wouldn't be included if it is technically feasible. I'm even more confused by the fact that there is a Latte preview image but no CSS file for it.
2. I'm not a fan of copying the [docs directory from catppuccin/catppuccin](https://github.com/42Willow/vitepress/tree/main/docs/src) into this repository, please remove this and add some other markdown content for the demo site.
3. A little bit unsure why the theme is defaulting to macchiato in the [index.js](https://github.com/42Willow/vitepress/blob/997e89d5ba6b0d63b3bef2930b97ed5182317cae/theme/index.js#L2-L4) as we don't do that elsewhere. Please update this to default to mocha, if I'm understanding this correctly.
4. It would be a lot nicer if the code for the example site was in a subdirectory instead of being at the root level and inside `/docs`. 

	Could you try to restructure the repository as outlined below? 

	```sh
	.
	├── assets
	│   ├── frappe.webp
	│   ├── latte.webp
	│   ├── macchiato.webp
	│   ├── mocha.webp
	│   └── preview.webp
	├── example
	│   ├── bun.lockb
	│   ├── package.json (for demo site)
	│   ├── src
	│   │   └── index.md
	│   └── tsconfig.json
	├── LICENSE
	├── package.json (for publishing to npm)
	├── README.md
	├── theme
	│   ├── frappe.css
	│   ├── index.js
	│   ├── macchiato.css
	│   └── mocha.css
	└── vitepress.tera
	```

No. 4 is more of a refactoring exercise that can be carried out at later point but I'd be happy to merge if No. 1 -> No. 3 were explained / implemented.

Thanks!

**Comment by uncenter** [comment]
> Can we add a section on the FAQ on why Latte isn't included? I'm assuming this is because of a technical limitation of some sort? I can't think of any reason why Latte wouldn't be included if it is technically feasible. I'm even more confused by the fact that there is a Latte preview image but no CSS file for it.

Below the usage section there is a note that says:

> Frappe is included in all flavors as the light mode variant.

I believe that is a typo and is meant to say latte.

**Comment by 42Willow** [comment]
Thanks for the detailed feedback and advice :)

> I believe that is a typo and is meant to say latte.
Oops sorry that’s a typo.

I am currently on holidays so I will get back to the feedback and finishing the port soon.

**Comment by 42Willow** [comment]
I have no idea what I'm doing so could someone please take a look at https://github.com/42Willow/vitepress?
I've tried to take on the feedback but I have limited experience with this stuff.

Using css to override the accent colour doesn't seem like the most elegant way to do it :thinking: 
https://github.com/42Willow/vitepress/tree/main/example/.vitepress/theme

**Comment by uncenter** [comment]
Can you make it so a single var `var(--ctp-accent)` changes those three brand colors?

**Comment by sgoudham** [comment]
Hey again :wave:,
Just looking to understand where this port is at right now.

> I have no idea what I'm doing so could someone please take a look at [42Willow/vitepress](https://github.com/42Willow/vitepress)?
I've tried to take on the feedback but I have limited experience with this stuff.

Were you able to get some help on this @42Willow?

**Comment by 42Willow** [comment]
Hi, thanks for the reminder. I just need to invest some time into finishing off this port (I have been a little busy recently)

I was thinking of theming the CSS variables directly with JS/TS (similar to how [daisyui](https://github.com/catppuccin/daisyui/blob/main/src/index.ts) does it) rather than using whiskers for templating - I am a little unsure about how I'd go about having the accent and flavour configurable.

I'll have some time to look into this in an hour or so

**Comment by 42Willow** [comment]
Should be ready

**Comment by uncenter** [comment]
Theme looks good to me! We: added callout/alerts/admonition styling; added a step for setting (and set in the demo site) the markdown syntax highlighting theme to Catppuccin; added variables that themed the copy/copied clipboard icons; changed the demo site accent color to mauve; and did some documentation glow-ups!

**Comment by sgoudham** [comment]
Hey again 👋,
Took the time to have a look at again and it looks amazing! Great job @42Willow and @uncenter!

One comment from me regarding the theme:

1. I found that the current "line-highlighted" colour for codeblocks is a bit harsh on Latte:

	![image](https://github.com/user-attachments/assets/eaea776c-6eeb-47d3-86ad-808a1f35a11f)

	From inspect element, it looks like the variable is `--vp-code-line-highlight-color`. It'd be great if that was themed to match the "selection-background" key on the style guide:
	
	![image](https://github.com/user-attachments/assets/724d3b1a-7197-4b2d-b9ff-d39be6014ea4)

One comment (_nitpick_) from me regarding the codebase:

1. It'd be great if we could move away from `bun` as the package manager since Renovate cannot currently raise dependency update PRs since the lockfile is in a binary format. I know there are plans on bun's side to move away from this but I'd still like to move away if that's fine. I don't personally mind what the replacement but it seems like `pnpm` is winning across the organisation so that makes sense to me to recommend.

Overall, looks really great. Since my comments aren't too substantial, I'm happy to approve this theme for transfer! I'm also happy to help set up release please on this repository which can be responsible for publishing to NPM.

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by 42Willow** [comment]
I've made the changes and submitted a PR to add it to ports.yml [here](https://github.com/catppuccin/catppuccin/pull/2537) :)

**Comment by 42Willow** [comment]
(I transferred the repo btw)
I don't have `main` branch rw permissions I'm not sure if that's intended - I need to update the links from `42willow/vitepress` to `catppuccin/vitepress`

**Comment by uncenter** [comment]
> (I transferred the repo btw) I don't have `main` branch rw permissions I'm not sure if that's intended - I need to update the links from `42willow/vitepress` to `catppuccin/vitepress`

The main branch permission is a ruleset for all ports/repositories, make a pull request for changes. Makes for easier visibility of changes in the org as PRs/comments would should up in the Discord server GitHub feed and people can chime in or leave comments.

**Comment by 42Willow** [comment]
makes sense, must've changed since 4 months ago if I remember correctly?

**Comment by uncenter** [comment]
Probably a bit farther back (6 months?) or so but yeah something like that. I found it annoying at first but it is cool to see what everyone is working on across the org and you can poke in and see what changes are being made :)
