### ISSUE TITLE
KiCad

### ISSUE THREAD

**Issue by waterlilly-lilly** [catppuccin/catppuccin#2443]
### Link to repository

https://github.com/waterlilly-lilly/catppuccin-kicad

### Screenshots

Previews are [here](https://github.com/waterlilly-lilly/catppuccin-kicad/tree/main/assets/previews)

### Any additional comments?

- `metadata.json` will have to be updated with Catppuccin metadata, alongside README
- Need to make a .zip release by running `zip -r catppuccin-kicad.zip *` in the root directory of the repository because KiCad doesn't support the metadata.json file being in a directory within the zip file
- Naming of the files in `colors` may be iffy; especially the spaces and the accent in Frappé
- Preview images use the `kit-dev-coldfire-xilinx_5213` demo included with KiCad, which has a remote chance of having licensing concerns (though other color themes use it)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by 21st-centuryman** [comment]
This is awesome. I loved the way it looks. I hope this gets merged 

If they do merge it you could try adding this to KiCad's official PCM. This would make installation easier

https://dev-docs.kicad.org/en/addons/index.html
https://gitlab.com/kicad/addons/metadata

**Comment by sgoudham** [comment]
I think @backwardspy was meaning to give it a try earlier on but may have forgotten. 

FYI, this is not required for transfer but it would certainly make for an easier review on my end if the repository was converted to use [catppuccin/whiskers](https://github.com/catppuccin/whiskers) which is our port creation tool that makes it much nicer to create and maintain Catppuccin themes.

**Comment by waterlilly-lilly** [comment]
Updated to use whiskers and added a justfile build script.

**Comment by sgoudham** [comment]
Thanks for going ahead and doing that @waterlilly-lilly. 
Just scanning the `.tera` file, is there an intentional decision to not use Catppuccin variables for much of the file? 
I would have expected that all of the `rgb()` values would be driven from the Catppuccin flavour variables.

**Comment by waterlilly-lilly** [comment]
Many of those are for lesser-used functionality (i.e. projects with large amounts of layers, user-defined layers) or, in the case of 3D Viewer, colors that are meant to reflect real-world appearances. Colors for the majority of core functionality is implemented. I could have just used the nearest palette color for the currently undefined cases, but that could lead to legibility problems; for the time being I just left them as the default values. Suggestions on how to handle those cases are welcome.

**Comment by sgoudham** [comment]
Noted, thanks for the quick reply and that makes sense! I've just installed KiCad and can confirm that the theme is able to be imported on my end.

I just have 2 comments about the codebase:

1. Please delete the [.gitkeep](https://github.com/waterlilly-lilly/catppuccin-kicad/blob/main/assets/.gitkeep) file and you can move the previews from assets/previews/ directly into assets/.
2. The README has a broken link to the releases page, I believe the link should be `https://github.com/waterlilly-lilly/catppuccin-kicad/releases/latest`

Since my notes are very minor and improvements/fixes to the theme can be made later on, I'm happy to approve this repository for transfer into the organisation! Additionally, if you don't mind, I'd like for this repository to use [release-please](https://github.com/googleapis/release-please) after transfer for its release management as it's something we're starting to use widely across the organisation. 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by waterlilly-lilly** [comment]
I've made the two fixes, and will keep in mind to start using the Conventional Commits specification for Release Please purposes.
