### ISSUE TITLE
Miniflux - A lightweight RSS reader

### ISSUE THREAD

**Issue by mark-pitblado** [catppuccin/catppuccin#2461]
### Link to repository

https://github.com/mark-pitblado/miniflux

### Screenshots

<img width="1437" alt="latte" src="https://github.com/catppuccin/catppuccin/assets/86988982/7204c1ca-485e-4eb3-9981-3e6a3d7ae8c5">
<img width="1440" alt="frappe" src="https://github.com/catppuccin/catppuccin/assets/86988982/2326c812-3ec3-45c0-b7f8-f3abd4d87254">
<img width="1440" alt="macchiato" src="https://github.com/catppuccin/catppuccin/assets/86988982/20153139-d3c0-4f66-ad2a-a1f3fe363a83">
<img width="1440" alt="mocha" src="https://github.com/catppuccin/catppuccin/assets/86988982/49bf1df6-3474-4182-9b36-ed4fc4e947cf">

### Any additional comments?

Miniflux is a lightweight RSS reader. Was previously MIT licensed. Shields are setup for catppuccin org, not exactly clear on the details of the handoff process.

I plan to make some further improvements, particularly with the latte theme for readability, while trying to keep the same colour for the same function across all 4 themes.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hi, thanks for your contribution! this all looks great.

i'd be happy to accept this as it stands, but i thought i'd ask first; is there any room for our [css](https://github.com/catppuccin/palette/blob/main/docs/css.md) or [sass](https://github.com/catppuccin/palette/blob/main/docs/sass.md) ports to be used here? would it make maintenance any easier?

let me know your thoughts.

**Comment by sgoudham** [comment]
I was also taking a look at this @backwardspy, I agree with you but also recognise that generating 4 files from css/sass is a bit annoying at the minute. Requiring a javascript based approach with either node or deno iirc.

As for the port itself, I'm a little unsure. A lot of the CSS seems to be related to _layout_ changes (e.g. line-height, padding, borders, margin, etc) instead of purely applying the colour scheme? I'm not familar with Miniflux but it feels odd that we're making so many, dare I say opinionated, changes for a colourscheme port. Wouldn't we want to keep our changes related to just the colours? I mention this as I know we're trying to move away from opinionated configurations in our ports.

A few comments beside that:

- Please keep the files from the [catppuccin/template](https://github.com/catppuccin/template) repository, especially the `LICENSE` file.
- Some of the highlights can better match our [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md). In particular. links should be `blue` and I believe we use `lavender` for hover and `mauve` for visited. Error should be `red`, etc.

**Comment by mark-pitblado** [comment]
Wow thanks for taking a look so quickly! I'm on vacation so will probably be able to get a lot of this done today for you.

1. @backwardspy I just tested it out with the import and it works fine, the only improvement would be a reduction in the 9 or so lines of code at the top that define the colours, but happy to incorporate! I am slightly partial to keeping the raw hexcodes, because if the user does end up wanting to switch down the line away from catppuccin it might make it easier for them? For someone just starting out the concept of the import might be a barrier.
2. Very valid point about the extra non-colour related css. Some of the elements that the colour theme is applied to may not exist without it, but I will do a before and after and put here for review.
3. I can make the improvements for the style guide, and will also see if I can make the latte theme more readable at the same time.

**Comment by mark-pitblado** [comment]
Okay I believe I have addressed all of the points raised.

1. Turns out my eyes just didn't catch the difference on the colour I tested from the default for the application, using `@import` doesn't seem to be handled by the application. Therefore hex codes will be needed.
2. I have removed all non-colour related css, most were just small tweaks and application still looks fine.
3. LICENSE file from template was reinstated. I had removed it as I was unsure how long the process would take, and didn't want to have the copyright claim there until it was ready to go.
4. I have toned down the colours to improve readability across all four themes, and aligned with style guide for *most* links. Since there are so many links on the page, if everything was blue it might get a bit overwhelming. For example, in a corporate blog with a specific byline, mauve and green are used to contrast the elements

<img width="876" alt="green-authour" src="https://github.com/catppuccin/catppuccin/assets/86988982/3e25ec2b-f5ee-48ee-963b-d93a189498e2">


The file layout for the `.css` files is aimed to be:

(Top) Define colours. These are the only lines that need to change between the four themes
(Middle) Apply colours using readable descriptors
(End) Match readable descriptors to custom colours

This should enable the user to change colours for specific elements easily as everything they would need to modify is at the bottom.

**Comment by mark-pitblado** [comment]
Hi @backwardspy, just following up on this as it's been a while,  is there anything I could do further? If it's a busy time or holidays completely understand

**Comment by sgoudham** [comment]
Hey @mark-pitblado, apologies for not replying earlier. @backwardspy is a bit busy at the moment so feel free to ping me going forward.

> using @import doesn't seem to be handled by the application. Therefore hex codes will be needed.

That's a shame. In that case, we might possibly want a workflow based on https://github.com/catppuccin/whiskers in order to generate all of the CSS files. A prior example of this is something like [catppuccin/vimium](https://github.com/catppuccin/vimium/blob/main/vimium.tera).

In any case, we can try to make the port more maintainable later on. No need to block the transfer of the repository on that 👍 

> I have removed all non-colour related css, most were just small tweaks and application still looks fine.

Thank you for doing this!

> LICENSE file from template was reinstated.

Thanks! One tiny nitpick from me is that the `LICENSE.md` should just be a `LICENSE` file without any file extension. I'd appreciate if you could update that 👍 

> I have toned down the colours to improve readability across all four themes, and aligned with style guide for most links. Since there are so many links on the page, if everything was blue it might get a bit overwhelming. For example, in a corporate blog with a specific byline, mauve and green are used to contrast the elements

I really enjoy the new previews/style, thank you for making these changes! 

<hr>

My only nitpick was the file extension on the `LICENSE.md` file which can be easily changed upon transfer so I'm happy for it to be transferred over to the organisation! Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
