### ISSUE TITLE
Gitkraken

### ISSUE THREAD

**Issue by Paracetamol56** [catppuccin/catppuccin#2492]
### Link to repository

https://github.com/Askerad/catppuccin-gitkraken-theme

### Screenshots

![](https://github.com/Askerad/catppuccin-gitkraken-theme/raw/master/assets/latte.webp)
![](https://github.com/Askerad/catppuccin-gitkraken-theme/raw/master/assets/frappe.webp)
![](https://github.com/Askerad/catppuccin-gitkraken-theme/raw/master/assets/macchiato.webp)
![](https://github.com/Askerad/catppuccin-gitkraken-theme/raw/master/assets/mocha.webp)

### Any additional comments?

Hi,
I know there is an open issue for GitKraken (#2170) but we recently worked on this port with @Askerad.
It utilizes the Whiskers templating system to better respect the pallet and enhance maintainability.
Thank you for considering our contribution!

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by uncenter** [comment]
- You should probably link to https://help.gitkraken.com/gitkraken-desktop/themes/#custom-themes for the location of the custom themes directory instead of explicitly writing it in our README.
- Little thing but your [`editorconfig`](https://github.com/Askerad/catppuccin-gitkraken-theme/blob/master/editorconfig) file should begin with a dot: `.editorconfig`.
- In your Whiskers template, since you are using a matrix, you can get rid of the `flavor.colors.` part in front of every color (`red.hex` is the same as `flavor.colors.red.hex` here).

**Comment by Paracetamol56** [comment]
Thank you for your feedback! I appreciate your input.
I have addressed all the issues you mentioned in my last commit ([398017f](https://github.com/Askerad/catppuccin-gitkraken-theme/commit/398017f0e284f2ca4fb1914f54ef3862d3356ef0)).

**Comment by sgoudham** [comment]
Hey :wave:,

Thank you both for working on this, I tried it out earlier and it looks good! I have some concerns about readability on Latte but I think that's best raised as an improvement going forward since it is readable. #2170 has fallen a bit inactive so I think it makes sense to close that one as not planned and favour this repository instead.

A minor nitpick from me is to potentially re-order the colours for the graph to match either a set of the rainbow highlights specified in the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#rainbow-parameters--local-variables)

![image](https://github.com/user-attachments/assets/cd779a61-ce27-4284-b654-fb43c3b32075)

But I'm not too fussed about it and it can be easily changed afterwards due to the port using whiskers :+1: 

I'm happy for it to be transferred over to the organisation! I'll send you an invite to join the maintainers team so you can transfer the repository! Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by Paracetamol56** [comment]
Hi,
Thank you for your feedback and for trying out the port! 
We appreciate your concern about the readability on Latte, and I agree that it can be improved in future updates.
We'll address the minor issue you've raised before transferring the repository.
Thank you for the invite and the instructions.

**Comment by sgoudham** [comment]
Hey @askerad, I see that you have accepted the invite to the organisation and should now have permissions to transfer the repository over, let me know if you have any issues or questions with this process!

**Comment by Askerad** [comment]
Yeah sorry about the delay, the transfer is now done
