### ISSUE TITLE
Ghidra

### ISSUE THREAD

**Issue by AnicJov** [catppuccin/catppuccin#2504]
### Link to repository

https://github.com/AnicJov/ghidra

### Screenshots

![image](https://github.com/user-attachments/assets/3d50ad7d-7a0f-4b8c-8bef-e5ffa63727b1)

### Any additional comments?

Not a perfect looking theme by any means mostly because of the theming limitations of Ghidra, but I hope to get closer with future improvements to the theme and advancements in Ghidra's theming support.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by AnicJov** [comment]
Thanks to [uncenter](https://github.com/uncenter) we now have the other flavors too!
![preview.webp](https://raw.githubusercontent.com/AnicJov/ghidra/main/assets/previews/preview.webp)

**Comment by sgoudham** [comment]
Hey :wave:,
Sorry for the wait on this, great work! The previews look really great.

Just one comment on the codebase, please delete the [.gitkeep](https://github.com/AnicJov/ghidra/blob/main/assets/.gitkeep) file and you can move the previews from `assets/previews/` directly into `assets/`.

I'm not able to test the theme out right now but the mappings against the tokens seems well aligned with the style guide, evident through the preview images! Since I only have one minor comment that can be easily fixed later on, happy to approve this port for transfer into the organisation!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by AnicJov** [comment]
Hiya, no worries about the delay.

Thanks for reviewing the port!

I have made the suggested changes to the repo and joined the org.
I will read the doc and familiarize myself with the transfer process and complete it once I know what I'm doing :sweat_smile:

**Comment by AnicJov** [comment]
I transferred the repo. Do I update the `ports.yml` myself or do I wait for someone else to do it?

**Comment by backwardspy** [comment]
feel free to PR the change to ports.yml if you like! if not, one of us will do it eventually. 🙂
