### ISSUE TITLE
Ghostty

### ISSUE THREAD

**Issue by uncenter** [catppuccin/catppuccin#2530]
### Link to repository

https://github.com/uncenter/ctp-ghostty

### Screenshots

![image](https://github.com/user-attachments/assets/cb1533fb-0214-4568-8f2b-1c2c61b0337a)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:,

Thanks for the port, 2 tiny things from me:

1. The [selection background](https://github.com/uncenter/ctp-ghostty/blob/9ed20e85c51dbb763f26f1afd08d9d55b2389bce/ghostty.tera#L27) should be updated to match the style guide:

	![image](https://github.com/user-attachments/assets/c4c57520-5ff9-4cae-9c36-29a8d9e94230)

	(Sidenote, I think I should update that to mention that it can be mixed with `base` to achieve a similar affect.)

2. Might be a small nitpick but I don't think we should be using `[!TIP]` to mention that the themes are already included by default. It seems obvious to 99% of users that they should always follow that advice since it's much simpler. 

	If it's not too much hassle, I'd appreciate it if you could update the description to something similar like [catppuccin/the-archive's Usage section](https://github.com/catppuccin/the-archive#usage) where I also mentioned the same thing.

Definitely happy to approve after 1. is implemented and 2. can be a discussion point later on if you're really against it.

**Comment by uncenter** [comment]
Both should be done now!

**Comment by sgoudham** [comment]
Transfer it :+1:
