### ISSUE TITLE
Tumblr

### ISSUE THREAD

**Issue by stellophiliac** [catppuccin/catppuccin#2533]
### Link to repository

https://github.com/stellophiliac/ctp-tumblr

### Screenshots

![](https://github.com/stellophiliac/ctp-tumblr/raw/main/assets/preview.webp)

### Any additional comments?

Closes (..? resolves?) this [port request](https://github.com/catppuccin/catppuccin/discussions/2122#discussion-5446346)
The files require a timestamp to be added to be valid — I just pasted in the timestamp when I finished working on the template.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey 👋,
Thanks for your work on this, just tried it out and think it looks great!

One comment about the theme itself:

1. I'd change [white-on-dark](https://github.com/stellophiliac/ctp-tumblr/blob/e19a116ba2f5e6a41973e6638698e802696c9429/tumblr.tera#L15) to be `subtext0` instead of `overlay1` as I found that it results in much better contrast on all the flavours.

Two comments about the codebase:

1. Please delete the [.DS_STORE](https://github.com/stellophiliac/ctp-tumblr/blob/main/themes/.DS_Store) and [.gitkeep](https://github.com/stellophiliac/ctp-tumblr/blob/main/assets/.gitkeep) files.
2. You don't need to [set the palette variable](https://github.com/stellophiliac/ctp-tumblr/blob/e19a116ba2f5e6a41973e6638698e802696c9429/tumblr.tera#L9) anymore in recent versions of whiskers! You should be able to now reference it directly by just specifying the colour, e.g. `{{ mauve.rgb.r }}`. (You might want to keep the variable defined for when you specify the accent colours though)

Overall, great work! I'd be happy to approve once `overlay1` is changed to `subtext0` since the codebase changes aren't very intensive and can be carried out at anytime.

**Comment by stellophiliac** [comment]
requested changes should be all done!

**Comment by sgoudham** [comment]
Thanks, great work! I'm happy for it to be transferred over to the organisation!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by uncenter** [comment]
Is there a reason for the extra space at the end of the value for the `name` fields? https://github.com/stellophiliac/ctp-tumblr/blob/f472b9242826ec4518d7796c255ab8aeb2254427/tumblr.tera#L12

**Comment by uncenter** [comment]
I would also recommend using a [macro](https://keats.github.io/tera/docs/#macros) for the RGB values instead of repeating yourself every time. An example of this can be found at https://github.com/catppuccin/konsole/blob/3b64040e3f4ae5afb2347e7be8a38bc3cd8c73a8/konsole.tera#L9-L11.

**Comment by stellophiliac** [comment]
removed the space and transferred the repo! won't use a macro for now since i doubt significant changes will have to be made and replacing everything would take a bit of time

**Comment by sgoudham** [comment]
Thanks for transferring it, and yeah I didn't comment on the template basically due to how simple it is and how I don't really forsee it changing much in the future and if it does, we can deal with refactors like that then :+1:
