### ISSUE TITLE
Zen Browser

### ISSUE THREAD

**Issue by IAmJafeth** [catppuccin/catppuccin#2544]
### Link to repository

https://github.com/IAmJafeth/zen-browser

### Screenshots

![image](https://github.com/user-attachments/assets/38d36efa-cd37-4ab8-b765-a4c79f73a78c)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nyxkrage** [comment]
There's currently quite a lot of things that are unthemed from a quick glance at this.

<img width="192" alt="image" src="https://github.com/user-attachments/assets/ee3606cc-315c-4110-91f9-7f37142b2835">  

The main browser background has the color `rgb(238, 237, 237)` which isn't a catppuccin color.

<img width="728" alt="image" src="https://github.com/user-attachments/assets/0d5fc6a7-3140-4c7a-af98-8198cfe32251">  

In the settings, most of the background is themed, however control elements, like the search field, the checkboxes, radio buttons.  

<img width="728" alt="image" src="https://github.com/user-attachments/assets/55152bd7-1490-4052-b9a9-bcbe390e6ac7">  

In the privacy section of the settings these accordion options aren't properly themed.

<img width="228" alt="image" src="https://github.com/user-attachments/assets/10d4a8f9-d8b7-454c-ba9a-7dbd53673ce5">  

Links are colored as accent, the style guide says that links should be blue, and when hovered are not themed with a catppuccin color.

<img width="48" alt="image" src="https://github.com/user-attachments/assets/2984fb34-8e35-4995-8b44-548d97b9b861">  

The bookmark icon is not catppuccin themed.

<img width="494" alt="image" src="https://github.com/user-attachments/assets/1156634a-f611-4b58-8612-2ce7ada85c36">  

The buttons in the edit bookmark popup are not catppuccin colors.

<img width="377" alt="image" src="https://github.com/user-attachments/assets/3d440852-4032-4e73-9c88-23f8973c6646">  

The enable slider in the enhanced tracking popup is not catppuccin colors.

<img width="861" alt="image" src="https://github.com/user-attachments/assets/28e0f649-a80d-42da-bcd1-d3b2f57f9782">

The protections dashboard is also mostly unthemed.

The library and devtools are also unthemed, but I imagine that might not be possible to theme due to not directly being a part of the chrome.

**Comment by IAmJafeth** [comment]
Hey @nyxkrage,

Thanks for the detailed feedback, I really appreciate it! 
I am working on the fixes right now to have it ready and fully baked.

However, there are some styles that appear to be themed to me without doing any change yet, could you please let me know what OS did you use for your test? 
I observed this specifically in: 
- Links are colored as accent, but when hovered are not themed.
- The enable slider in the enhanced tracking popup is not catppuccin colors.

Regarding all other items, I am actively working on them right now. 

Hope I have an update soon!

**Comment by kzhe2059** [comment]
To add a slight "nitpick"
![image](https://github.com/user-attachments/assets/e95f07e4-a25d-451e-9045-84eba50810a6)
This button has poor contrast currently. Also, the motif of two accent bars on the sidebar is somewhat broken by the redesign of Zen browser as only the bottom "bar" is still present.

**Comment by sgoudham** [comment]
Hey :wave:,
Thanks for taking the time on working through those issues raised, really appreciated!

@nyxkrage told me earlier that he's happy from his end so I'm also happy to approve this port for transfer into the organisation!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
