### ISSUE TITLE
Hyprland

### ISSUE THREAD

**Issue by rubyowo** [catppuccin/catppuccin#255]
**Are you available to help in the creation of this port? 😄**
Yes

**Additional context 📷 (optional)**
https://github.com/rubyowo/hyprland

**Comment by andreasgrafen** [comment]
I think the header-link should point to the original source of the app, not the catppuccin repo since that's where the user already is, no? Other than that I'd assume that release will be added as soon as the project moved over to the org; just as this would fix the broken link for the screenshot? c:

Not using hyprland myself, technically I'd say the port looks good to me.
