### ISSUE TITLE
Where is my SDDM theme?

### ISSUE THREAD

**Issue by HeitorAugustoLN** [catppuccin/catppuccin#2553]
### Link to repository

https://github.com/HeitorAugustoLN/catppuccin-where-is-my-sddm-theme

### Screenshots

![Preview](https://github.com/user-attachments/assets/fb0a7eee-5902-4aba-af96-8fcbe3ad3d5e)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by HeitorAugustoLN** [comment]
Any updates?

**Comment by sgoudham** [comment]
Hey :wave:,
Apologies on the wait for the review on this.

The repository looks good, thank you for following all of our guidelines for it!

As for the theme itself, I understand that this is supposed to be a minimalist theme. One of the concerns brought up in the review for hyprlock was how Catppuccin deals with ports which are "personalised dotfile configurations"

It would be great if you could update the preview screenshots to say "Catppuccin" or "Pepperjack" to make it feel more like a Catppuccin port instead of just someone's dotfiles being ported over. In the same vein, I see that we're setting a lot of options by default in the whiskers template. Ideally, our ports shouldn't touch anything outside of the colours of the theme as different users will want to change those anyways. It's good that you've mentioned how to override the options with whiskers but can I confirm that we aren't changing things like font size, blur radius, etc from their defaults?

I'd be happy to approve for transfer if the previews were updated to have a different name like "Catppuccin" and the default options can be resolved/discussed in the future.

**Comment by HeitorAugustoLN** [comment]
Updated the repo, without setting any other options by default, it doesn't show the user, so I updated the preview without any user, but if it is needed, I can make the user be shown and update it to have "Catppuccin" in it.

**Comment by sgoudham** [comment]
Thanks for updating the repository! @HeitorAugustoLN 

I actually didn't mind the customisation section, I didn't realise the defaults were so minimal but I suppose that makes sense. Regarding the username, I think it's fine as is but I think it would be good in the Usage section or in a FAQ section to link to some documentation on what options can be modified so that the user can tailor it to their own preferences? 

In any case, I think the port is good for transfer and it can be modified/iterated on afterwards. I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
