### ISSUE TITLE
wlogout

### ISSUE THREAD

**Issue by Anomalocaridid** [catppuccin/catppuccin#2591]
### Link to repository

https://github.com/Anomalocaridid/wlogout

### Screenshots

![composite screenshot of wlogout themed with all four catppuccin flavours](https://github.com/Anomalocaridid/wlogout/raw/main/assets/preview.webp)

### Any additional comments?

~~I also created a script, `generate_icons.sh`, that downloads the base icons from `wlogout` and `wleave` and recolors them into each flavor's text color. This script is run with `just icons`, but is not included in `just build`. This is because it takes a few minutes to run and requires an internet connection and an external dependency, `curl`.~~

Edit: The icons are now generated using whiskers.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:,

Thanks for your work on this. I've got 2 comments:

1. Please update [these links](https://github.com/Anomalocaridid/wlogout/blob/a47b3f310fd4ac4f7616be5266f974c3e1e41638/generate_icons.sh#L48-L49) to also specify a commit hash instead of the HEAD branch. It's worth mentioning that we could bring the icons in source and generate them via whiskers to avoid a bash script. There's some prior art in the organisation, mainly [catppuccin/cursors](https://github.com/catppuccin/cursors/tree/main/src/templates).
2. This is totally my fault for not documenting it but could you please update the previews to be `mauve` instead of `lavender` as that is the canonical default accent of Catppuccin.

Happy to approve for transfer after those 2 comments are resolved, thanks!

**Comment by Anomalocaridid** [comment]
How is it now?
1. I replaced the bash script with whiskers. All templates are in the `templates` directory and each icon has its own template, sorted by style. I also went ahead and added accent support to the theme and icons.
2. Actually, it was more my fault. I chose `lavender` because for some reason I thought the borders would be considered a window border. I have updated the previews to use `mauve` and reflect the accent support.

**Comment by sgoudham** [comment]
Thanks for making those changes! Nice to see the accent support included via whiskers.

I had a look at the previews and I can't help but feel that `mantle` would be nicer instead of the current [surface0](https://github.com/Anomalocaridid/wlogout/blob/6a045fee9465af6542d4a9498579a9a26d0443c3/templates/wlogout.tera#L23) used for the background of the buttons. Could you indulge me here and show screenshots of the theme with the button background as `mantle` instead?

**Comment by Anomalocaridid** [comment]
I agree that it looks a lot nicer, so I went ahead and changed the buttons' background to `mantle`, updating the previews accordingly.

**Comment by sgoudham** [comment]
So sorry, just one more thing that I'd like you to try.

Instead of [surface2](https://github.com/Anomalocaridid/wlogout/blob/4572f57572efa1e38eb2f35e289f9d4eba810b9e/templates/wlogout.tera#L32) as the hover background on button focus, could you maybe try the selection background highlight as defined in our style guide: 

![image](https://github.com/user-attachments/assets/5bf49907-3cfc-4626-8325-c7e5f8468ed0)

I'd have to imagine it would make the highlight less harsh on Latte and still look good on the darker flavours? If opacity isn't supported, you can technically "fake" it by mixing it with `base` or `mantle`. I'd appreciate it if you could indulge me once again, sorry!

**Comment by Anomalocaridid** [comment]
No worries. Now is as good a time as any to make improvements.

The buttons' selected background is now 20% `overlay2` and 80% `mantle`. I also selected another button in the previews in order to show what they look like in `macchiato` and `mocha` in the composite preview.

Also, while wlogout does support opacity, the background is already transparent, although it appears opaque in the previews. I still used `mix` to ensure the buttons' backgrounds are opaque because otherwise whatever is behind wlogout would show through the buttons, but only when they are selected.

**Comment by sgoudham** [comment]
Nice one, thanks for your work on this and the continued engagement. I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
