### ISSUE TITLE
OhMyREPL

### ISSUE THREAD

**Issue by Anomalocaridid** [catppuccin/catppuccin#2593]
### Link to repository

https://github.com/Anomalocaridid/ohmyrepl

### Screenshots

![screenshots of OhMyREPL themed with all four catppuccin flavors arranged in a grid](https://github.com/user-attachments/assets/e9f9333b-d4aa-4327-abde-7fab703ab072)

### Any additional comments?

In case it is relevant, for each of the screenshots, I already had the themes for each set before running any of the commands pictured. I mainly ran the commands to set the themes in an attempt to reduce the amount of negative space in each screenshot.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey 👋,
Nice work and thanks for using whiskers!

I agree with your decision on running the commands to reduce negative space in the screenshots, they look nice! Honestly no notes for the theme since the tera file looks good and follows the style guide.

The only things I noticed about the repository are:

1. The [`.gitkeep`](https://github.com/Anomalocaridid/ohmyrepl/blob/main/assets/.gitkeep) file should be removed. FYI, this file is only required when you want to push an empty folder to a remote repository.
2. The README should have a step that just says "Download the `catppuccin.jl` file to the config directory" or equivalent and it seems you can hardcode the "PATH/TO" bit in the codeblock

`1.` can be carried out after transfer and `2`. is more of a nit than anything else so happy to approve this repository for transfer! Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by Anomalocaridid** [comment]
Thank you!
