### ISSUE TITLE
Windows Terminal

### ISSUE THREAD

**Issue by LudoPinelli** [catppuccin/catppuccin#26]
Here is _catppuccin_ for **Windows Terminal**

![catppuccin_winterm](https://user-images.githubusercontent.com/93927273/148325253-0ed8fa10-84fe-48a2-87bb-0784185c970c.png)

## Config
```json
{
    "background": "#1E1E29",
    "black": "#6E6C7E",
    "blue": "#A4B9EF",
    "brightBlack": "#6E6C7E",
    "brightBlue": "#A4B9EF",
    "brightCyan": "#E5B4E2",
    "brightGreen": "#B1E3AD",
    "brightPurple": "#B4009E",
    "brightRed": "#E38C8F",
    "brightWhite": "#DADAE8",
    "brightYellow": "#EBDDAA",
    "cursorColor": "#B1E3AD",
    "cyan": "#E5B4E2",
    "foreground": "#DADAE8",
    "green": "#B1E3AD",
    "name": "Catppuccin",
    "purple": "#B4009E",
    "red": "#E38C8F",
    "selectionBackground": "#332E41",
    "white": "#DADAE8",
    "yellow": "#EBDDAA"
},
```
## Usage
1. Open the _Settings_ panel
2. Choose "Open the Json file" (bottom left corner)
3. Copy the content of the "catppuccin.json" into the json file:
```json
{
    ..default layout
    "schemes": 
    [
        ..catppuccin layout
        ..other layouts
    ],
}
```
4. Save and exit
5. Select the profile you want _catppuccin_ to be applied to
6. Select "Appearance"
7. Choose _catppuccin_ in the _theme_ drop down menu
8. Click on "Save", done!

**Are you available to help in the creation of this port? 😄 (optional)**
Yes, but I'm pretty new to the github world so it's still a bit difficult for me to understand how to do things properly and find my way around ^^

**Comment by LudoPinelli** [comment]
So, I made this [repo](https://github.com/LudoPinelli/catppuccin-windows-terminal) with the catppuccin/template, but since each app has its own repo I have no idea where/how to make a PR for it ^^

**Comment by Pocco81** [comment]
Hey Ludo! nice to meet you :)

So recently after a discussion in the discord server we standardized the colors that were supposed to be used for terminal ports, so I was wondering if you could update this. Instructions can be found here: https://github.com/catppuccin/style-guide#-terminals

And btw, why don't you join our Discord server? almost every discussion project-wise takes place there. I'd really encourage you to join us since it's also possible that other users of Window's terminal might provide you a better feedback than I could ever do (I don't use Windows.)

Here is the link: https://discord.gg/r6Mdz5dpFc

**Comment by LudoPinelli** [comment]
Here is the updated standardize version: https://github.com/LudoPinelli/windows-terminal :)
