### ISSUE TITLE
Obsidian.md

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#4]
Apart from making theme I gotta sort out how to publish it on their official store.

**Comment by VictorTennekes** [comment]
How to add the theme is described in their 'Demo & Help' Vault:

" If you're proficient in CSS, another way is to contribute a theme, so that people who don't know CSS can enjoy your work. If you decide to do so, feel free to share it on the #css-themes channel on Discord, or in the Share & Showcase category on our forum.

If you'd like to add your theme to the community theme list, let us know! (Or we might reach out to you first!) "

**Comment by mbeckrich** [comment]
I've been playing around with a Catppuccin Obsidian theme since finding the iTerm one. Happy to attach a couple screenshots and do a PR if that's not stepping on any toes. I tried to keep color use consistent, but wasn't sure which ones belonged where. That's not too difficult to change around, though.

![Screen Shot 2022-01-02 at 12 26 32 AM](https://user-images.githubusercontent.com/88514414/147869189-0422705b-41d2-40eb-8079-7e33b5f549f6.png)
![Screen Shot 2022-01-02 at 12 28 59 AM](https://user-images.githubusercontent.com/88514414/147869191-7c2df901-aea1-4460-a36c-fe74a91a85ca.png)
.

**Comment by mimishahzad** [comment]
I can help with adding the theme to Obsidian's store, do you have a repo on github for it? you just need to clone their repo and edit the readme, and then open a pull request. This theme lokos awesome by the way from the screenshots!

**Comment by mbeckrich** [comment]
> I can help with adding the theme to Obsidian's store, do you have a repo on github for it? you just need to clone their repo and edit the readme, and then open a pull request. This theme looks awesome by the way from the screenshots!

Hey, thanks! I have actually just redone the theme with the colors in the updated style guide. This makes the background a bit bluer, but otherwise not a ton has changed. I will plan on getting a repo up for it this evening, appreciate the heads up on how to handle their store.

**Comment by mbeckrich** [comment]
Alright, theme is up here: https://github.com/mbeckrich/obsidian Appreciate any constructive feedback and, if there aren't any objections, I'll plan on getting it into their theme store this week.

**Comment by Pocco81** [comment]
@mbeckrich awesome! I just sent you an invitation to the org. After accepting it you should be able to move the repo :D

**Comment by mbeckrich** [comment]
@Pocco81 great! I just submitted a PR for store approval. This is done by updating a json they have, which requires my username/reponame. I didn't think about how the transfer would affect the repo's url. :( I'll plan on waiting for them to merge the PR, then get it updated once we do the transfer? But lmk if there's a better way to handle this.

**Comment by mbeckrich** [comment]
@Pocco81 looks like the old url to my repo redirects to the catppuccin org's repo (sorry, never done that before :) ), so I've just gone ahead and done the transfer. They've still not merged the PR but I'll adjust it if necessary.

**Comment by Pocco81** [comment]
Although your PR hasn't been merged, I think it's safe to say that the port is "ready."

**Comment by Pocco81** [comment]
Although your PR hasn't been merged, I think it's safe to say that the port is "ready."
