### ISSUE TITLE
Fuchsia Cursor

### ISSUE THREAD

**Issue by DewenHona** [catppuccin/catppuccin#67]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
[Fuchsia Theme](https://www.pling.com/p/1544830/)

**Comment by Pocco81** [comment]
I don't know how viable something like this would be. Because doing this will require us to distribute the piece of software. Unlike programs that read this type of data from config files, this ain't got no logic.

But now imagine other scenarios where they (Fuchsia creator(s)) change the border radius of the mice. We would have to recolour every sprite... Again...

I this case we'd be better off making an icon pack.
